'use strict';

/**
 * Property 4: IR serialization round-trip
 *
 * For any valid CommandIR object (generated by genIR):
 * 1. serialize(ir) → JSON string
 * 2. deserialize(json) → restored IR
 * 3. The restored IR SHALL be deeply equal to the original IR
 * 4. Emitting from the restored IR SHALL produce output identical
 *    to emitting from the original IR
 *
 * **Validates: Requirements 3.2, 3.3**
 *
 * @module tests/properties/ir-roundtrip.test
 */

const { test } = require('node:test');
const { deepStrictEqual } = require('node:assert/strict');

const { forAll } = require('../lib/pbt.js');
const { genIR } = require('../generators/ir-gen.js');
const { serialize, deserialize } = require('../../lib/ir.js');
const { emit: emitKiro } = require('../../lib/emitters/kiro.js');
const { emit: emitCursor } = require('../../lib/emitters/cursor.js');

// Feature: multi-ide-adapter-layer, Property 4: IR serialization round-trip
test('IR round-trip: serialize→deserialize produces structurally equal IR', () => {
    forAll(
        'IR structural round-trip',
        genIR,
        (ir) => {
            const json = serialize(ir);
            const restored = deserialize(json);

            // Structural equality: restored IR must deeply equal original
            try {
                deepStrictEqual(restored, ir);
            } catch (e) {
                return false;
            }
            return true;
        },
        { iterations: 100 }
    );
});

// Feature: multi-ide-adapter-layer, Property 4: IR serialization round-trip
test('IR round-trip: emit from restored IR equals emit from original (Kiro)', () => {
    forAll(
        'IR functional round-trip (Kiro emitter)',
        genIR,
        (ir) => {
            const json = serialize(ir);
            const restored = deserialize(json);

            const output1 = emitKiro(ir, { maxLines: 500 });
            const output2 = emitKiro(restored, { maxLines: 500 });

            // Functional equivalence: emitted output must be identical
            try {
                deepStrictEqual(output1, output2);
            } catch (e) {
                return false;
            }
            return true;
        },
        { iterations: 100 }
    );
});

// Feature: multi-ide-adapter-layer, Property 4: IR serialization round-trip
test('IR round-trip: emit from restored IR equals emit from original (Cursor)', () => {
    forAll(
        'IR functional round-trip (Cursor emitter)',
        genIR,
        (ir) => {
            const json = serialize(ir);
            const restored = deserialize(json);

            const output1 = emitCursor(ir, { maxLines: 500 });
            const output2 = emitCursor(restored, { maxLines: 500 });

            // Functional equivalence: emitted output must be identical
            try {
                deepStrictEqual(output1, output2);
            } catch (e) {
                return false;
            }
            return true;
        },
        { iterations: 100 }
    );
});
