'use strict';

/**
 * Property-Based Tests for the Kiro Emitter.
 *
 * Validates correctness properties 5, 6, 7, 8, 9, and 11 from the
 * design document against the Kiro emitter implementation.
 *
 * Uses Node.js built-in test runner with simple iteration-based
 * property tests (100 iterations minimum per property).
 *
 * @module tests/properties/kiro-emitter-properties.test.js
 */

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { randomInt } = require('node:crypto');
const { createCommandIR, VALID_TOOLS } = require('../../lib/ir.js');
const { emit } = require('../../lib/emitters/kiro.js');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

const ITERATIONS = 100;

const TOOL_TRANSLATIONS = {
    Agent: 'invoke_sub_agent',
    Read: 'read_file',
    Glob: 'file_search',
    AskUserQuestion: 'chat',
    Explore: 'context-gatherer',
    Plan: 'plan',
};

const CLAUDE_CODE_RAW_PATTERNS = [
    /\bAgent\s*\(/,
    /\bRead\s*\(/,
    /\bGlob\s*\(/,
    /\bAskUserQuestion\s*\(/,
    /\bExplore\s*\(/,
];

const MD_HEADER =
    '<!-- Auto-generated by generate-adapters — do not edit manually -->';

// ---------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------

/**
 * Pick a random element from an array.
 * @param {unknown[]} arr
 * @returns {unknown}
 */
function pick(arr) {
    return arr[randomInt(arr.length)];
}

/**
 * Generate a random alphanumeric string of the given length.
 * @param {number} [len]
 * @returns {string}
 */
function randomString(len) {
    const length = len || randomInt(3, 20);
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars[randomInt(chars.length)];
    }
    return result;
}

/**
 * Generate a random tool reference.
 * @param {string} [tool] - Specific tool, or random if omitted
 * @returns {import('../../lib/ir.js').ToolReference}
 */
function genToolReference(tool) {
    const t = tool || pick(VALID_TOOLS);
    const params = {};
    if (t === 'Agent') {
        params.subagent_type = 'general-task-execution';
        params.description = `Task: ${randomString(10)}`;
    } else if (t === 'Read') {
        params._positional = `context/${randomString(6)}.md`;
    } else if (t === 'Glob') {
        params._positional = `**/*.${randomString(2)}`;
    } else if (t === 'AskUserQuestion') {
        params._positional = `What is ${randomString(5)}?`;
    } else if (t === 'Explore') {
        params._positional = `src/${randomString(5)}`;
    } else if (t === 'Plan') {
        params._positional = `Plan ${randomString(6)}`;
    }
    return {
        tool: t,
        context: `${t} call context`,
        lineNumber: randomInt(1, 200),
        parameters: params,
    };
}

/**
 * Generate a random delegation call.
 * @returns {import('../../lib/ir.js').DelegationCall}
 */
function genDelegation() {
    return {
        agentType: 'general-task-execution',
        promptTemplate: `Implement ${randomString(8)} feature`,
    };
}

/**
 * Generate a random process step.
 * @param {number} stepNumber
 * @param {Object} [opts]
 * @param {boolean} [opts.withDelegation]
 * @returns {import('../../lib/ir.js').ProcessStep}
 */
function genProcessStep(stepNumber, opts = {}) {
    const toolCount = randomInt(0, 4);
    const toolRefs = [];
    for (let i = 0; i < toolCount; i++) {
        toolRefs.push(genToolReference());
    }
    const delegations = opts.withDelegation ? [genDelegation()] : [];
    return {
        stepNumber,
        title: `Step ${stepNumber}: ${randomString(8)}`,
        body: `Body content for step ${stepNumber}: ${randomString(20)}`,
        toolReferences: toolRefs,
        delegations,
    };
}

/**
 * Generate a random CommandIR with configurable properties.
 * @param {Object} [opts]
 * @param {number} [opts.stepCount]
 * @param {boolean} [opts.withDelegation]
 * @param {string[]} [opts.tools] - Specific tools to include
 * @param {string[]} [opts.contextFiles]
 * @returns {import('../../lib/ir.js').CommandIR}
 */
function genIR(opts = {}) {
    const stepCount =
        opts.stepCount !== undefined ? opts.stepCount : randomInt(1, 8);
    const name = `cmd-${randomString(6)}`;
    const ir = createCommandIR(name);

    ir.frontmatter.description = `Test command: ${randomString(10)}`;
    ir.role.title = `Role ${randomString(5)}`;
    ir.role.description = `Description ${randomString(15)}`;
    ir.task.goal = `Goal: ${randomString(10)}`;
    ir.task.body = `Body: ${randomString(15)}`;

    // Context files
    const contextFiles =
        opts.contextFiles || [`context/spec/${randomString(5)}/tasks.md`];
    ir.io.contextFiles = contextFiles;

    // Process steps
    for (let i = 1; i <= stepCount; i++) {
        ir.process.steps.push(
            genProcessStep(i, { withDelegation: opts.withDelegation })
        );
    }

    // Top-level tool references
    if (opts.tools) {
        for (const tool of opts.tools) {
            ir.toolReferences.push(genToolReference(tool));
        }
    } else {
        const toolCount = randomInt(1, 5);
        for (let i = 0; i < toolCount; i++) {
            ir.toolReferences.push(genToolReference());
        }
    }

    return ir;
}

// ---------------------------------------------------------------------
// Property Tests
// ---------------------------------------------------------------------

describe('Kiro Emitter Properties', () => {
    /**
     * **Validates: Requirements 4.2, 4.3**
     *
     * Property 5: Tool translation correctness per Provider (Kiro)
     *
     * For any IR containing Claude Code tool references, the Kiro emitter
     * output SHALL contain the Kiro-native equivalent for each tool
     * reference and SHALL NOT contain raw Claude Code tool syntax.
     */
    describe('Property 5: Tool translation correctness (Kiro)', () => {
        it('Agent → invoke_sub_agent for all iterations', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ tools: ['Agent'], withDelegation: true });
                ir.process.steps[0].toolReferences.push(
                    genToolReference('Agent')
                );
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                assert.ok(
                    allContent.includes('invoke_sub_agent'),
                    `Iteration ${i}: output must contain invoke_sub_agent`
                );
            }
        });

        it('Read → read_file for all iterations', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ tools: ['Read'] });
                ir.process.steps[0].toolReferences.push(
                    genToolReference('Read')
                );
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                assert.ok(
                    allContent.includes('read_file'),
                    `Iteration ${i}: output must contain read_file`
                );
            }
        });

        it('Glob → file_search for all iterations', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ tools: ['Glob'] });
                ir.process.steps[0].toolReferences.push(
                    genToolReference('Glob')
                );
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                assert.ok(
                    allContent.includes('file_search'),
                    `Iteration ${i}: output must contain file_search`
                );
            }
        });

        it('AskUserQuestion → plain-text chat prompt for all iterations', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ tools: ['AskUserQuestion'] });
                ir.process.steps[0].toolReferences.push(
                    genToolReference('AskUserQuestion')
                );
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                assert.ok(
                    allContent.includes('Ask the user directly in chat'),
                    `Iteration ${i}: output must contain plain-text chat prompt`
                );
            }
        });

        it('Explore → context-gatherer agent for all iterations', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ tools: ['Explore'] });
                ir.process.steps[0].toolReferences.push(
                    genToolReference('Explore')
                );
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                assert.ok(
                    allContent.includes('context-gatherer'),
                    `Iteration ${i}: output must contain context-gatherer`
                );
            }
        });

        it('output SHALL NOT contain raw Claude Code tool syntax', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({
                    tools: ['Agent', 'Read', 'Glob', 'AskUserQuestion', 'Explore'],
                });
                // Add tool refs into steps too
                for (const step of ir.process.steps) {
                    step.toolReferences.push(genToolReference());
                }
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');
                for (const pattern of CLAUDE_CODE_RAW_PATTERNS) {
                    assert.ok(
                        !pattern.test(allContent),
                        `Iteration ${i}: output must not contain raw ` +
                        `Claude Code syntax matching ${pattern}`
                    );
                }
            }
        });
    });

    /**
     * **Validates: Requirements 4.5**
     *
     * Property 6: Path reference integrity
     *
     * All references to project documents SHALL use workspace-relative
     * context/ paths, and all generated file paths SHALL be contained
     * within .awos-adapters/.
     */
    describe('Property 6: Path reference integrity', () => {
        it('context file references use workspace-relative context/ paths', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const contextFiles = [
                    `context/${randomString(4)}/${randomString(5)}.md`,
                    `context/spec/${randomString(4)}/tasks.md`,
                ];
                const ir = genIR({ contextFiles });
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');

                // All context references should appear without leading ./ or /
                for (const cf of contextFiles) {
                    assert.ok(
                        allContent.includes(cf),
                        `Iteration ${i}: content must reference ${cf}`
                    );
                }
                // No absolute paths
                assert.ok(
                    !allContent.includes('/home/'),
                    `Iteration ${i}: must not contain absolute paths`
                );
                assert.ok(
                    !allContent.includes('/Users/'),
                    `Iteration ${i}: must not contain absolute paths`
                );
            }
        });

        it('all generated file paths are within steering/ or hooks/', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ withDelegation: randomInt(0, 2) === 1 });
                const result = emit(ir);
                for (const file of result.files) {
                    assert.ok(
                        file.relativePath.startsWith('steering/') ||
                        file.relativePath.startsWith('hooks/'),
                        `Iteration ${i}: file path "${file.relativePath}" ` +
                        'must start with steering/ or hooks/'
                    );
                }
            }
        });
    });

    /**
     * **Validates: Requirements 4.6**
     *
     * Property 7: File size invariant
     *
     * No generated output file SHALL exceed 500 lines.
     */
    describe('Property 7: File size invariant', () => {
        it('no output file exceeds 500 lines for typical commands', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                // Generate IRs with realistic step counts and body sizes
                const stepCount = randomInt(1, 10);
                const ir = genIR({
                    stepCount,
                    withDelegation: randomInt(0, 2) === 1,
                });
                // Add moderate body content to steps (realistic sizes)
                for (const step of ir.process.steps) {
                    const extraLines = randomInt(2, 15);
                    const lines = [];
                    for (let j = 0; j < extraLines; j++) {
                        lines.push(`Line ${j}: ${randomString(20)}`);
                    }
                    step.body += '\n' + lines.join('\n');
                }
                const result = emit(ir);
                for (const file of result.files) {
                    const lineCount = file.content.split('\n').length;
                    assert.ok(
                        lineCount <= 500,
                        `Iteration ${i}: file "${file.relativePath}" has ` +
                        `${lineCount} lines, exceeds 500-line limit`
                    );
                }
            }
        });

        it('lineCount property matches actual content lines', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ stepCount: randomInt(1, 6) });
                const result = emit(ir);
                for (const file of result.files) {
                    const actualLines = file.content.split('\n').length;
                    assert.equal(
                        file.lineCount,
                        actualLines,
                        `Iteration ${i}: file "${file.relativePath}" ` +
                        `lineCount (${file.lineCount}) does not match ` +
                        `actual (${actualLines})`
                    );
                }
            }
        });
    });

    /**
     * **Validates: Requirements 4.6 (via 6.4 process encoding)**
     *
     * Property 8: Process step encoding
     *
     * For any CommandIR with N process steps, the Kiro emitter SHALL
     * produce output where each process step is addressable as an
     * individual unit, count of emitted units SHALL equal count of
     * process steps in the IR.
     */
    describe('Property 8: Process step encoding', () => {
        it('emitted step count equals IR step count', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const stepCount = randomInt(1, 10);
                const ir = genIR({ stepCount });
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');

                // Each step produces a "### Step N:" heading in the output
                let foundSteps = 0;
                for (let s = 1; s <= stepCount; s++) {
                    if (allContent.includes(`### Step ${s}:`)) {
                        foundSteps++;
                    }
                }
                assert.equal(
                    foundSteps,
                    stepCount,
                    `Iteration ${i}: expected ${stepCount} step headings, ` +
                    `found ${foundSteps}`
                );
            }
        });
    });

    /**
     * **Validates: Requirements 9.2, 9.4**
     *
     * Property 9: Delegation strategy correctness (Kiro)
     *
     * When emitting the implement command's Agent delegation calls,
     * output SHALL use invoke_sub_agent and SHALL include task completion
     * tracking instructions (marking checkboxes in tasks.md).
     */
    describe('Property 9: Delegation strategy correctness (Kiro)', () => {
        it('delegation uses invoke_sub_agent with general-task-execution', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ withDelegation: true });
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');

                assert.ok(
                    allContent.includes('invoke_sub_agent'),
                    `Iteration ${i}: must contain invoke_sub_agent`
                );
                assert.ok(
                    allContent.includes('general-task-execution'),
                    `Iteration ${i}: must reference general-task-execution ` +
                    'agent type'
                );
            }
        });

        it('includes task completion tracking instructions', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({ withDelegation: true });
                const result = emit(ir);
                const allContent = result.files
                    .map((f) => f.content)
                    .join('\n');

                assert.ok(
                    allContent.includes('tasks.md'),
                    `Iteration ${i}: must reference tasks.md for tracking`
                );
                assert.ok(
                    allContent.includes('[ ]') || allContent.includes('[x]'),
                    `Iteration ${i}: must include checkbox marking instructions`
                );
            }
        });
    });

    /**
     * **Validates: Requirements 14.3**
     *
     * Property 11: Auto-generated header presence
     *
     * Every file produced SHALL begin with a header comment stating
     * "Auto-generated by generate-adapters — do not edit manually".
     */
    describe('Property 11: Auto-generated header presence', () => {
        it('every output file begins with the auto-generated header', () => {
            for (let i = 0; i < ITERATIONS; i++) {
                const ir = genIR({
                    withDelegation: randomInt(0, 2) === 1,
                });
                const result = emit(ir);
                assert.ok(
                    result.files.length > 0,
                    `Iteration ${i}: emitter must produce at least one file`
                );
                for (const file of result.files) {
                    assert.ok(
                        file.content.startsWith(MD_HEADER),
                        `Iteration ${i}: file "${file.relativePath}" must ` +
                        `start with header. Got: "${file.content.slice(0, 80)}"`
                    );
                }
            }
        });
    });
});
