'use strict';

/**
 * Property-Based Tests for Structural Validation Detection (Property 13).
 *
 * Validates that for any generated adapter file containing a structural
 * violation of its Provider's rules, the validator reports the violation
 * with Provider name, file path, and the rule that was violated.
 *
 * **Validates: Requirements 16.1**
 *
 * @module tests/properties/validation-properties.test.js
 */

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { randomInt } = require('node:crypto');
const { forAll } = require('../lib/pbt.js');
const { createGeneratedFile } = require('../../lib/emitters/base-emitter.js');
const { validate } = require('../../lib/validator.js');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

const HEADER_TEXT =
    'Auto-generated by generate-adapters — do not edit manually';

const PROVIDERS = ['kiro', 'cursor', 'codex', 'cline', 'continue'];

/**
 * Valid extension expectations per provider directory.
 */
const PROVIDER_DIRS = {
    kiro: { dir: 'steering', validExt: '.md', invalidExts: ['.txt', '.js'] },
    cursor: { dir: 'rules', validExt: '.md', invalidExts: ['.txt', '.yaml'] },
    codex: { dir: 'tasks', validExt: '.md', invalidExts: ['.json', '.txt'] },
    cline: { dir: 'rules', validExt: '.md', invalidExts: ['.js', '.yaml'] },
    continue: {
        dir: 'config',
        validExt: '.md',
        invalidExts: ['.txt', '.yaml'],
    },
};

// ---------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------

/**
 * Generate a random string.
 * @param {number} len
 * @returns {string}
 */
function randomString(len) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < len; i++) {
        result += chars[randomInt(chars.length)];
    }
    return result;
}

/**
 * Generate a file with a wrong extension violation for a provider.
 *
 * @param {object} rng - PBT random number generator
 * @returns {{provider: string, file: object, violationType: string}}
 */
function genWrongExtensionFile(rng) {
    const provider = rng.pick(PROVIDERS);
    const config = PROVIDER_DIRS[provider];
    const badExt = rng.pick(config.invalidExts);
    const fileName = `test-${randomString(5)}${badExt}`;
    const relativePath = `${config.dir}/${fileName}`;

    let content;
    if (provider === 'continue') {
        // Continue expects JSON; give it a non-JSON file in wrong ext
        content = `<!-- ${HEADER_TEXT} -->\n\nSome non-JSON content.`;
    } else {
        content = `<!-- ${HEADER_TEXT} -->\n\n# Test File\n\nContent here.`;
    }

    const file = createGeneratedFile(relativePath, content);

    return { provider, file, violationType: 'wrong-extension' };
}

/**
 * Generate a file missing the auto-generated header.
 *
 * @param {object} rng - PBT random number generator
 * @returns {{provider: string, file: object, violationType: string}}
 */
function genMissingHeaderFile(rng) {
    const provider = rng.pick(PROVIDERS);
    const config = PROVIDER_DIRS[provider];
    const fileName = `test-${randomString(5)}${config.validExt}`;
    const relativePath = `${config.dir}/${fileName}`;

    let content;
    if (config.validExt === '.json') {
        // JSON files without auto-generated header
        content = '{"name": "test", "value": 42}';
    } else {
        content = `# Test File\n\nNo header here.\n`;
    }

    const file = createGeneratedFile(relativePath, content);

    return { provider, file, violationType: 'missing-header' };
}

/**
 * Generate a file exceeding the 500-line limit.
 *
 * @param {object} rng - PBT random number generator
 * @returns {{provider: string, file: object, violationType: string}}
 */
function genOversizedFile(rng) {
    const provider = rng.pick(PROVIDERS);
    const config = PROVIDER_DIRS[provider];
    const fileName = `test-${randomString(5)}${config.validExt}`;
    const relativePath = `${config.dir}/${fileName}`;

    const lineCount = rng.int(501, 600);
    let content;
    if (config.validExt === '.json') {
        const lines = [`// ${HEADER_TEXT}`];
        lines.push('{');
        for (let i = 0; i < lineCount - 3; i++) {
            lines.push(`  "field${i}": "value${i}",`);
        }
        lines.push('}');
        content = lines.join('\n');
    } else {
        const lines = [`<!-- ${HEADER_TEXT} -->`];
        lines.push('');
        lines.push('# Large Test File');
        for (let i = 0; i < lineCount - 3; i++) {
            lines.push(`Line ${i}: ${randomString(10)}`);
        }
        content = lines.join('\n');
    }

    const file = createGeneratedFile(relativePath, content);

    return { provider, file, violationType: 'oversized' };
}

/**
 * Generate a valid file that should produce no violations.
 *
 * @param {object} rng - PBT random number generator
 * @returns {{provider: string, file: object}}
 */
function genValidFile(rng) {
    const provider = rng.pick(PROVIDERS);
    const config = PROVIDER_DIRS[provider];
    const fileName = `test-${randomString(5)}${config.validExt}`;
    const relativePath = `${config.dir}/${fileName}`;

    let content;
    if (config.validExt === '.json') {
        content = `// ${HEADER_TEXT}\n{"name": "test", "value": 42}`;
    } else {
        content = `<!-- ${HEADER_TEXT} -->\n\n# Valid File\n\nContent.`;
    }

    const file = createGeneratedFile(relativePath, content);

    return { provider, file };
}

// ---------------------------------------------------------------------
// Property 13: Structural validation detection
// ---------------------------------------------------------------------

describe('Property 13: Structural validation detection', () => {
    // Feature: multi-ide-adapter-layer, Property 13
    it('validator detects wrong file extension violations', () => {
        forAll(
            'wrong extension detected',
            genWrongExtensionFile,
            (input) => {
                const violations = validate(input.provider, [input.file]);

                // Must have at least one violation
                if (violations.length === 0) {
                    return false;
                }

                // Each violation must include provider name, file path, and rule
                for (const v of violations) {
                    if (v.provider !== input.provider) return false;
                    if (!v.filePath || v.filePath.length === 0) return false;
                    if (!v.rule || v.rule.length === 0) return false;
                }

                // At least one violation must reference the file
                const fileViolation = violations.some(
                    (v) => v.filePath === input.file.relativePath
                );
                return fileViolation;
            },
            { iterations: 100 }
        );
    });

    it('validator detects missing auto-generated header', () => {
        forAll(
            'missing header detected',
            genMissingHeaderFile,
            (input) => {
                const violations = validate(input.provider, [input.file]);

                // Must find the header violation
                const headerViolation = violations.some(
                    (v) =>
                        v.filePath === input.file.relativePath &&
                        v.rule.toLowerCase().includes('header')
                );

                if (!headerViolation) return false;

                // All violations must have provider, filePath, rule
                for (const v of violations) {
                    if (v.provider !== input.provider) return false;
                    if (!v.filePath) return false;
                    if (!v.rule) return false;
                }

                return true;
            },
            { iterations: 100 }
        );
    });

    it('validator detects files exceeding 500-line limit', () => {
        forAll(
            'oversized file detected',
            genOversizedFile,
            (input) => {
                const violations = validate(input.provider, [input.file]);

                // Must find the size violation
                const sizeViolation = violations.some(
                    (v) =>
                        v.filePath === input.file.relativePath &&
                        v.rule.toLowerCase().includes('500')
                );

                if (!sizeViolation) return false;

                // All violations must include required fields
                for (const v of violations) {
                    if (v.provider !== input.provider) return false;
                    if (!v.filePath) return false;
                    if (!v.rule) return false;
                }

                return true;
            },
            { iterations: 100 }
        );
    });

    it('validator reports no violations for valid files', () => {
        forAll(
            'valid files pass',
            genValidFile,
            (input) => {
                const violations = validate(input.provider, [input.file]);

                // No violations for properly formed files
                return violations.length === 0;
            },
            { iterations: 100 }
        );
    });

    it('violations always include provider name, file path, and rule', () => {
        forAll(
            'violation structure completeness',
            genWrongExtensionFile,
            (input) => {
                const violations = validate(input.provider, [input.file]);

                for (const v of violations) {
                    // Provider name must be non-empty string matching input
                    if (typeof v.provider !== 'string') return false;
                    if (v.provider !== input.provider) return false;

                    // File path must be non-empty string
                    if (typeof v.filePath !== 'string') return false;
                    if (v.filePath.length === 0) return false;

                    // Rule must be non-empty string
                    if (typeof v.rule !== 'string') return false;
                    if (v.rule.length === 0) return false;
                }

                return true;
            },
            { iterations: 100 }
        );
    });
});
