'use strict';

/**
 * Base Emitter module for the multi-IDE adapter layer.
 *
 * Provides shared utilities, contracts, and delegation strategy types
 * used by all Provider-specific emitters. Each Provider emitter imports
 * these helpers to produce consistent EmitResult objects.
 *
 * @module lib/emitters/base-emitter
 */

const path = require('node:path');
const { getAutoGeneratedHeader } = require('../ir.js');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

/**
 * The root output directory for all generated adapter files.
 * @type {string}
 */
const ADAPTERS_ROOT = '.awos-adapters';

/**
 * Delegation strategy type constants.
 * @enum {string}
 */
const DELEGATION_TYPES = Object.freeze({
    /** IDE supports native subagent spawning (e.g. Kiro invoke_sub_agent). */
    SUBAGENT: 'subagent',
    /** IDE requires sequential prompt/task execution. */
    SEQUENTIAL: 'sequential',
    /** IDE cannot automate delegation; user must run tasks manually. */
    MANUAL: 'manual',
});

// ---------------------------------------------------------------------
// EmitResult & EmitWarning Factories
// ---------------------------------------------------------------------

/**
 * @typedef {Object} EmitResult
 * @property {GeneratedFile[]} files - Files to write
 * @property {EmitWarning[]} warnings - Non-fatal issues
 */

/**
 * @typedef {Object} GeneratedFile
 * @property {string} relativePath - Path relative to .awos-adapters/{provider}/
 * @property {string} content - File content to write
 * @property {number} lineCount - Pre-computed line count
 */

/**
 * @typedef {Object} EmitWarning
 * @property {string} message - Human-readable warning description
 * @property {string} [file] - File path related to the warning
 * @property {string} [source] - Source location or context
 */

/**
 * @typedef {Object} DelegationStrategy
 * @property {'subagent'|'sequential'|'manual'} type - Strategy type
 * @property {function(DelegationCall): string} translate - Translates a
 *   delegation call into Provider-native instructions
 */

/**
 * @typedef {Object} DelegationCall
 * @property {string} agentType - The agent type to delegate to
 * @property {string} promptTemplate - The prompt/instruction template
 */

/**
 * Create a fresh EmitResult with empty files and warnings arrays.
 *
 * @returns {EmitResult}
 */
function createEmitResult() {
    return { files: [], warnings: [] };
}

/**
 * Create an EmitWarning object.
 *
 * @param {string} message - Warning description
 * @param {string} [file] - Related file path
 * @param {string} [source] - Source context
 * @returns {EmitWarning}
 */
function createEmitWarning(message, file, source) {
    if (typeof message !== 'string' || message.length === 0) {
        throw new Error('createEmitWarning: message must be a non-empty string');
    }
    const warning = { message };
    if (file !== undefined) {
        warning.file = file;
    }
    if (source !== undefined) {
        warning.source = source;
    }
    return warning;
}

// ---------------------------------------------------------------------
// GeneratedFile Factory
// ---------------------------------------------------------------------

/**
 * Create a GeneratedFile with auto-computed lineCount.
 *
 * @param {string} relativePath - Path relative to .awos-adapters/{provider}/
 * @param {string} content - File content
 * @returns {GeneratedFile}
 */
function createGeneratedFile(relativePath, content) {
    if (typeof relativePath !== 'string' || relativePath.length === 0) {
        throw new Error(
            'createGeneratedFile: relativePath must be a non-empty string'
        );
    }
    if (typeof content !== 'string') {
        throw new Error('createGeneratedFile: content must be a string');
    }
    return {
        relativePath,
        content,
        lineCount: countLines(content),
    };
}

// ---------------------------------------------------------------------
// Shared Utilities
// ---------------------------------------------------------------------

/**
 * Prepend the auto-generated header comment to content.
 * Inserts a blank line between the header and the body content.
 * Returns content unchanged if format is 'json' (no comments in JSON).
 *
 * @param {string} content - The file body content
 * @param {'js'|'md'|'yaml'|'json'} [format='md'] - File format for header
 * @returns {string} Content with header prepended
 */
function prependHeader(content, format = 'md') {
    const header = getAutoGeneratedHeader(format);
    if (!header) {
        return content;
    }
    return `${header}\n\n${content}`;
}

/**
 * Normalize a context path to be workspace-relative.
 * Strips leading `./`, leading `/`, and any `.awos-adapters/` prefix.
 * Ensures the path starts with `context/` when referencing shared state.
 *
 * @param {string} inputPath - Raw path to normalize
 * @returns {string} Workspace-relative normalized path
 */
function normalizeContextPath(inputPath) {
    if (typeof inputPath !== 'string' || inputPath.length === 0) {
        throw new Error(
            'normalizeContextPath: inputPath must be a non-empty string'
        );
    }

    let normalized = inputPath;

    // Normalize path separators to forward slashes
    normalized = normalized.split(path.sep).join('/');

    // Strip leading ./ or /
    normalized = normalized.replace(/^\.\//, '').replace(/^\//, '');

    // Strip .awos-adapters/ prefix if present (shouldn't reference adapter
    // internals from context paths)
    normalized = normalized.replace(/^\.awos-adapters\//, '');

    return normalized;
}

/**
 * Resolve an output file path for a Provider.
 * Produces paths relative to the workspace root under
 * `.awos-adapters/{provider}/...`.
 *
 * @param {string} provider - Provider name (e.g. 'kiro', 'cursor')
 * @param {string} relativePath - Path relative to the provider directory
 * @returns {string} Full path relative to workspace root
 */
function resolveOutputPath(provider, relativePath) {
    if (typeof provider !== 'string' || provider.length === 0) {
        throw new Error(
            'resolveOutputPath: provider must be a non-empty string'
        );
    }
    if (typeof relativePath !== 'string' || relativePath.length === 0) {
        throw new Error(
            'resolveOutputPath: relativePath must be a non-empty string'
        );
    }

    // Normalize and join using forward slashes for consistent output
    const cleanRelative = relativePath
        .replace(/^\.\//, '')
        .replace(/^\//, '');

    return `${ADAPTERS_ROOT}/${provider}/${cleanRelative}`;
}

// ---------------------------------------------------------------------
// Delegation Strategy Helpers
// ---------------------------------------------------------------------

/**
 * Create a delegation strategy for a Provider.
 *
 * @param {'subagent'|'sequential'|'manual'} type - Strategy type
 * @param {function(DelegationCall): string} translate - Translation function
 * @returns {DelegationStrategy}
 */
function createDelegationStrategy(type, translate) {
    const validTypes = Object.values(DELEGATION_TYPES);
    if (!validTypes.includes(type)) {
        throw new Error(
            `createDelegationStrategy: type must be one of: ${validTypes.join(', ')}`
        );
    }
    if (typeof translate !== 'function') {
        throw new Error(
            'createDelegationStrategy: translate must be a function'
        );
    }
    return { type, translate };
}

/**
 * Base translate function for delegation calls.
 * Returns a generic instruction string. Provider emitters override this
 * with their specific translation logic.
 *
 * @param {DelegationCall} delegation - The delegation call to translate
 * @returns {string} Generic delegation instruction
 */
function baseTranslate(delegation) {
    if (!delegation || typeof delegation !== 'object') {
        throw new Error('baseTranslate: delegation must be a non-null object');
    }
    const agent = delegation.agentType || 'general-task-execution';
    const prompt = delegation.promptTemplate || '';
    return `Delegate to agent "${agent}": ${prompt}`.trim();
}

// ---------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------

/**
 * Count the number of lines in a string.
 *
 * @param {string} content
 * @returns {number}
 */
function countLines(content) {
    if (!content) {
        return 0;
    }
    return content.split('\n').length;
}

// ---------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------

module.exports = {
    // Constants
    ADAPTERS_ROOT,
    DELEGATION_TYPES,

    // Factories
    createEmitResult,
    createEmitWarning,
    createGeneratedFile,
    createDelegationStrategy,

    // Utilities
    prependHeader,
    normalizeContextPath,
    resolveOutputPath,
    baseTranslate,
    countLines,
};
