'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');

const { emit, createClineDelegationStrategy } = require('../lib/emitters/cline.js');
const { createCommandIR } = require('../lib/ir.js');

/**
 * Build a realistic sample IR for the implement command.
 */
function buildSampleIR() {
    const ir = createCommandIR('implement');
    ir.frontmatter.description =
        'Runs tasks — delegates coding to sub-agents, tracks progress.';
    ir.role.title = 'Lead Implementation Agent';
    ir.role.description =
        'You are a Lead Implementation Agent responsible for executing tasks.';
    ir.role.rules = ['Always track progress', 'Delegate appropriately'];
    ir.task.goal = 'Execute the pending work for a given specification.';
    ir.io.contextFiles = [
        'context/spec/[index]-[name]/functional-spec.md',
        'context/spec/[index]-[name]/tasks.md',
    ];
    ir.io.outputs = [
        { name: 'tasks.md', description: 'Updated with completed checkboxes' },
    ];
    ir.interaction.tools = ['AskUserQuestion'];
    ir.interaction.notes = 'Use AskUserQuestion for multiple-choice questions';
    ir.process.steps = [
        {
            stepNumber: 1,
            title: 'Load Context',
            body: 'Read the tasks.md file.',
            toolReferences: [
                {
                    tool: 'Read',
                    context: 'Read tasks.md',
                    lineNumber: 10,
                    parameters: { _positional: 'context/spec/test/tasks.md' },
                },
            ],
            delegations: [],
        },
        {
            stepNumber: 2,
            title: 'Delegate Implementation',
            body: 'Delegate the next task to a sub-agent.',
            toolReferences: [
                {
                    tool: 'Agent',
                    context: 'Agent(subagent_type=coder)',
                    lineNumber: 30,
                    parameters: { subagent_type: 'coder' },
                },
            ],
            delegations: [
                {
                    agentType: 'coder',
                    promptTemplate: 'Implement the feature as specified.',
                },
            ],
        },
    ];
    ir.toolReferences = [
        { tool: 'Read', context: 'Read tasks.md', lineNumber: 10, parameters: {} },
        { tool: 'Agent', context: 'Agent()', lineNumber: 30, parameters: {} },
        {
            tool: 'AskUserQuestion',
            context: 'AskUserQuestion',
            lineNumber: 5,
            parameters: {},
        },
    ];
    return ir;
}

test('Cline emitter: module loads and exports emit + createClineDelegationStrategy', () => {
    assert.equal(typeof emit, 'function');
    assert.equal(typeof createClineDelegationStrategy, 'function');
});

test('Cline emitter: emit() produces rule file and memory bank template', () => {
    const ir = buildSampleIR();
    const result = emit(ir);

    assert.ok(result.files.length >= 2, 'Should produce at least 2 files');

    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );
    assert.ok(ruleFile, 'Should produce a rule file');
    assert.equal(ruleFile.relativePath, 'rules/implement.md');

    const memFile = result.files.find((f) =>
        f.relativePath.startsWith('memory-bank/')
    );
    assert.ok(memFile, 'Should produce a memory bank template');
    assert.equal(memFile.relativePath, 'memory-bank/implement-state.md');
});

test('Cline emitter: all files have auto-generated header', () => {
    const ir = buildSampleIR();
    const result = emit(ir);

    for (const f of result.files) {
        assert.ok(
            f.content.startsWith('<!-- Auto-generated by generate-adapters'),
            `File ${f.relativePath} should start with auto-generated header`
        );
    }
});

test('Cline emitter: all files are under 500 lines', () => {
    const ir = buildSampleIR();
    const result = emit(ir);

    for (const f of result.files) {
        assert.ok(
            f.lineCount <= 500,
            `File ${f.relativePath} has ${f.lineCount} lines (max 500)`
        );
    }
});

test('Cline emitter: rule file maps ROLE to Cline system prompt', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('## System Prompt'),
        'Rule file should contain System Prompt section'
    );
    assert.ok(
        ruleFile.content.includes('Lead Implementation Agent'),
        'System prompt should contain the role title'
    );
});

test('Cline emitter: rule file encodes auto-approve patterns for context/', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('## Auto-Approve Patterns'),
        'Rule file should contain auto-approve patterns section'
    );
    assert.ok(
        ruleFile.content.includes('context/**/*'),
        'Should include context/ read pattern'
    );
    assert.ok(
        ruleFile.content.includes('context/spec/**/*.md'),
        'Should include context/spec write pattern'
    );
});

test('Cline emitter: rule file uses workspace-relative context/ paths', () => {
    const ir = buildSampleIR();
    const result = emit(ir);

    for (const f of result.files) {
        assert.ok(
            !f.content.includes('.awos-adapters/context'),
            `File ${f.relativePath} should not have .awos-adapters/ prefix in context paths`
        );
    }
});

test('Cline emitter: rule file contains process steps as addressable units', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('### Step 1: Load Context'),
        'Should have Step 1 as addressable unit'
    );
    assert.ok(
        ruleFile.content.includes('### Step 2: Delegate Implementation'),
        'Should have Step 2 as addressable unit'
    );
});

test('Cline emitter: Agent tool translated to sequential task execution', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('Execute delegated task sequentially'),
        'Agent should be translated to sequential execution'
    );
    assert.ok(
        ruleFile.content.includes('memory bank'),
        'Should reference memory bank state tracking'
    );
});

test('Cline emitter: includes task completion tracking', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('Task Completion Tracking'),
        'Should include task completion tracking section'
    );
    assert.ok(
        ruleFile.content.includes('`[ ]` → `[x]`'),
        'Should mention checkbox marking'
    );
});

test('Cline emitter: memory bank template tracks step progress', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const memFile = result.files.find((f) =>
        f.relativePath.startsWith('memory-bank/')
    );

    assert.ok(
        memFile.content.includes('## Step Progress'),
        'Memory bank should have step progress section'
    );
    assert.ok(
        memFile.content.includes('- [ ] Step 1: Load Context'),
        'Should track Step 1'
    );
    assert.ok(
        memFile.content.includes('- [ ] Step 2: Delegate Implementation'),
        'Should track Step 2'
    );
});

test('Cline emitter: memory bank template tracks delegated tasks', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const memFile = result.files.find((f) =>
        f.relativePath.startsWith('memory-bank/')
    );

    assert.ok(
        memFile.content.includes('## Delegated Tasks'),
        'Memory bank should have delegated tasks section'
    );
    assert.ok(
        memFile.content.includes('- [ ] coder'),
        'Should track coder delegation'
    );
});

test('Cline emitter: createClineDelegationStrategy returns sequential strategy', () => {
    const strategy = createClineDelegationStrategy();

    assert.equal(strategy.type, 'sequential');
    assert.equal(typeof strategy.translate, 'function');

    const translated = strategy.translate({
        agentType: 'coder',
        promptTemplate: 'Build the feature',
    });

    assert.ok(
        translated.includes('coder'),
        'Translation should reference agent type'
    );
    assert.ok(
        translated.includes('memory bank'),
        'Translation should mention memory bank'
    );
    assert.ok(
        translated.includes('tasks.md'),
        'Translation should mention tasks.md checkbox tracking'
    );
});

test('Cline emitter: Read tool translated to file read instruction', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('Read the file:'),
        'Read tool should produce file read instruction'
    );
});

test('Cline emitter: interaction notes translate tool names', () => {
    const ir = buildSampleIR();
    const result = emit(ir);
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );

    assert.ok(
        ruleFile.content.includes('Chat question'),
        'AskUserQuestion should be translated to Chat question'
    );
    assert.ok(
        !ruleFile.content.includes('AskUserQuestion'),
        'Raw Claude Code tool name should not appear'
    );
});

test('Cline emitter: works with minimal IR (no delegations)', () => {
    const ir = createCommandIR('spec');
    ir.role.title = 'Spec Writer';
    ir.role.description = 'Creates specifications.';
    ir.task.goal = 'Write a spec.';
    ir.process.steps = [
        {
            stepNumber: 1,
            title: 'Gather Requirements',
            body: 'Read existing docs.',
            toolReferences: [],
            delegations: [],
        },
    ];

    const result = emit(ir);

    assert.ok(result.files.length >= 2, 'Should still produce rule + memory bank');
    const ruleFile = result.files.find((f) =>
        f.relativePath.startsWith('rules/')
    );
    assert.ok(
        !ruleFile.content.includes('Task Completion Tracking'),
        'Should NOT include task completion when no delegations'
    );
});
