'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const {
    AUTO_GENERATED_HEADER,
    VALID_TOOLS,
    createCommandIR,
    serialize,
    deserialize,
    getAutoGeneratedHeader,
} = require('../lib/ir.js');

describe('lib/ir.js', () => {
    describe('AUTO_GENERATED_HEADER', () => {
        it('contains the expected message', () => {
            assert.equal(
                AUTO_GENERATED_HEADER,
                '// Auto-generated by generate-adapters — do not edit manually'
            );
        });
    });

    describe('VALID_TOOLS', () => {
        it('contains all six Claude Code tool types', () => {
            assert.deepEqual(VALID_TOOLS, [
                'Agent',
                'Read',
                'Glob',
                'AskUserQuestion',
                'Explore',
                'Plan',
            ]);
        });

        it('is frozen', () => {
            assert.throws(() => {
                VALID_TOOLS.push('Invalid');
            });
        });
    });

    describe('createCommandIR', () => {
        it('creates a valid IR with the given name', () => {
            const ir = createCommandIR('implement');
            assert.equal(ir.name, 'implement');
            assert.deepEqual(ir.frontmatter, {
                description: null,
                argumentHint: null,
            });
            assert.deepEqual(ir.role, { title: '', description: '', rules: [] });
            assert.deepEqual(ir.task, { goal: '', body: '' });
            assert.deepEqual(ir.io, {
                inputs: [],
                outputs: [],
                contextFiles: [],
            });
            assert.deepEqual(ir.interaction, { tools: [], notes: '' });
            assert.deepEqual(ir.process, { steps: [] });
            assert.deepEqual(ir.toolReferences, []);
        });

        it('throws on empty name', () => {
            assert.throws(
                () => createCommandIR(''),
                /name must be a non-empty string/
            );
        });

        it('throws on non-string name', () => {
            assert.throws(
                () => createCommandIR(123),
                /name must be a non-empty string/
            );
        });

        it('throws on null name', () => {
            assert.throws(
                () => createCommandIR(null),
                /name must be a non-empty string/
            );
        });
    });

    describe('serialize', () => {
        it('produces valid JSON from a CommandIR', () => {
            const ir = createCommandIR('test-cmd');
            const json = serialize(ir);
            const parsed = JSON.parse(json);
            assert.equal(parsed.name, 'test-cmd');
        });

        it('pretty-prints with 2-space indentation', () => {
            const ir = createCommandIR('test');
            const json = serialize(ir);
            assert.ok(json.includes('  "name"'));
        });

        it('throws on null input', () => {
            assert.throws(() => serialize(null), /ir must be a non-null object/);
        });

        it('throws on non-object input', () => {
            assert.throws(
                () => serialize('not an object'),
                /ir must be a non-null object/
            );
        });

        it('throws when ir.name is not a string', () => {
            assert.throws(
                () => serialize({ name: 42 }),
                /ir.name must be a string/
            );
        });
    });

    describe('deserialize', () => {
        it('round-trips a valid CommandIR', () => {
            const ir = createCommandIR('round-trip');
            ir.frontmatter.description = 'A test command';
            ir.role.title = 'Test Agent';
            ir.role.description = 'Does testing';
            ir.role.rules = ['Be thorough'];
            ir.task.goal = 'Run tests';
            ir.task.body = 'Execute all test suites';
            ir.io.inputs = [
                { name: 'TestFile', optional: false, source: '$ARGUMENTS' },
            ];
            ir.io.outputs = [
                { name: 'report.md', description: 'Test results' },
            ];
            ir.io.contextFiles = ['context/spec/tasks.md'];
            ir.interaction.tools = ['AskUserQuestion'];
            ir.interaction.notes = 'Ask before destructive actions';
            ir.process.steps = [
                {
                    stepNumber: 1,
                    title: 'Load context',
                    body: 'Read the spec files',
                    toolReferences: [
                        {
                            tool: 'Read',
                            context: 'Read tasks.md',
                            lineNumber: 10,
                            parameters: {},
                        },
                    ],
                    delegations: [],
                },
            ];
            ir.toolReferences = [
                {
                    tool: 'Read',
                    context: 'Read tasks.md',
                    lineNumber: 10,
                    parameters: {},
                },
            ];

            const json = serialize(ir);
            const restored = deserialize(json);
            assert.deepEqual(restored, ir);
        });

        it('throws on non-string input', () => {
            assert.throws(
                () => deserialize(123),
                /input must be a JSON string/
            );
        });

        it('throws on invalid JSON', () => {
            assert.throws(
                () => deserialize('{not valid json}'),
                /invalid JSON/
            );
        });

        it('throws when name is missing', () => {
            const obj = { ...createCommandIR('x') };
            delete obj.name;
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /name must be a string/
            );
        });

        it('throws when frontmatter is missing', () => {
            const obj = { ...createCommandIR('x') };
            delete obj.frontmatter;
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /frontmatter must be a non-null object/
            );
        });

        it('throws when role is missing', () => {
            const obj = { ...createCommandIR('x') };
            delete obj.role;
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /role must be a non-null object/
            );
        });

        it('throws when process steps have invalid structure', () => {
            const obj = createCommandIR('x');
            obj.process.steps = [{ stepNumber: 'not-a-number' }];
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /stepNumber must be a number/
            );
        });

        it('throws on invalid tool reference tool type', () => {
            const obj = createCommandIR('x');
            obj.toolReferences = [
                {
                    tool: 'InvalidTool',
                    context: 'test',
                    lineNumber: 1,
                    parameters: {},
                },
            ];
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /tool must be one of/
            );
        });

        it('throws on delegation with missing agentType', () => {
            const obj = createCommandIR('x');
            obj.process.steps = [
                {
                    stepNumber: 1,
                    title: 'Test',
                    body: 'Body',
                    toolReferences: [],
                    delegations: [{ promptTemplate: 'hello' }],
                },
            ];
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /agentType must be a string/
            );
        });

        it('validates io.inputs structure', () => {
            const obj = createCommandIR('x');
            obj.io.inputs = [{ name: 'Test' }]; // missing optional and source
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /optional must be a boolean/
            );
        });

        it('validates io.outputs structure', () => {
            const obj = createCommandIR('x');
            obj.io.outputs = [{ name: 'file.md' }]; // missing description
            assert.throws(
                () => deserialize(JSON.stringify(obj)),
                /description must be a string/
            );
        });
    });

    describe('getAutoGeneratedHeader', () => {
        it('returns JS comment by default', () => {
            const header = getAutoGeneratedHeader();
            assert.equal(
                header,
                '// Auto-generated by generate-adapters — do not edit manually'
            );
        });

        it('returns JS comment for "js" format', () => {
            const header = getAutoGeneratedHeader('js');
            assert.ok(header.startsWith('//'));
        });

        it('returns HTML comment for "md" format', () => {
            const header = getAutoGeneratedHeader('md');
            assert.ok(header.startsWith('<!--'));
            assert.ok(header.endsWith('-->'));
        });

        it('returns YAML comment for "yaml" format', () => {
            const header = getAutoGeneratedHeader('yaml');
            assert.ok(header.startsWith('# '));
        });

        it('returns empty string for "json" format', () => {
            const header = getAutoGeneratedHeader('json');
            assert.equal(header, '');
        });
    });
});
