'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { validate, VALIDATION_RULES } = require('../lib/validator.js');

describe('lib/validator.js', () => {
    describe('VALIDATION_RULES', () => {
        it('exports an array of rules', () => {
            assert.ok(Array.isArray(VALIDATION_RULES));
            assert.ok(VALIDATION_RULES.length > 0);
        });

        it('each rule has provider, description, and check function', () => {
            for (const rule of VALIDATION_RULES) {
                assert.equal(typeof rule.provider, 'string');
                assert.equal(typeof rule.description, 'string');
                assert.equal(typeof rule.check, 'function');
            }
        });

        it('includes universal rules (provider = "*")', () => {
            const universal = VALIDATION_RULES.filter(
                (r) => r.provider === '*'
            );
            assert.ok(universal.length >= 2);
        });

        it('includes rules for all five providers', () => {
            const providers = new Set(
                VALIDATION_RULES.map((r) => r.provider)
            );
            assert.ok(providers.has('kiro'));
            assert.ok(providers.has('cursor'));
            assert.ok(providers.has('codex'));
            assert.ok(providers.has('cline'));
            assert.ok(providers.has('continue'));
        });
    });

    describe('validate() — input validation', () => {
        it('throws on empty provider string', () => {
            assert.throws(
                () => validate('', []),
                /provider must be a non-empty string/
            );
        });

        it('throws on non-string provider', () => {
            assert.throws(
                () => validate(123, []),
                /provider must be a non-empty string/
            );
        });

        it('throws on non-array files', () => {
            assert.throws(
                () => validate('kiro', 'bad'),
                /files must be an array/
            );
        });

        it('returns empty array for empty file list', () => {
            const result = validate('kiro', []);
            assert.deepEqual(result, []);
        });
    });

    describe('validate() — universal rules', () => {
        it('flags files exceeding 500 lines', () => {
            const file = {
                relativePath: 'steering/big.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n' +
                    'x\n'.repeat(501),
                lineCount: 502,
            };
            const violations = validate('kiro', [file]);
            const sizeViolation = violations.find((v) =>
                v.rule.includes('500 lines')
            );
            assert.ok(sizeViolation);
            assert.equal(sizeViolation.provider, 'kiro');
            assert.equal(sizeViolation.filePath, 'steering/big.md');
            assert.ok(sizeViolation.suggestedFix.includes('502'));
        });

        it('passes files at exactly 500 lines', () => {
            const file = {
                relativePath: 'steering/ok.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n' +
                    'x\n'.repeat(499),
                lineCount: 500,
            };
            const violations = validate('kiro', [file]);
            const sizeViolation = violations.find((v) =>
                v.rule.includes('500 lines')
            );
            assert.equal(sizeViolation, undefined);
        });

        it('flags files missing auto-generated header', () => {
            const file = {
                relativePath: 'steering/no-header.md',
                content: '# Just content\nNo header here.',
                lineCount: 2,
            };
            const violations = validate('kiro', [file]);
            const headerViolation = violations.find((v) =>
                v.rule.includes('header')
            );
            assert.ok(headerViolation);
            assert.equal(headerViolation.provider, 'kiro');
        });

        it('accepts JS-style header', () => {
            const file = {
                relativePath: 'tasks/impl.md',
                content:
                    '// Auto-generated by generate-adapters' +
                    ' — do not edit manually\n# Task',
                lineCount: 2,
            };
            const violations = validate('codex', [file]);
            const headerViolation = violations.find((v) =>
                v.rule.includes('header')
            );
            assert.equal(headerViolation, undefined);
        });

        it('accepts HTML comment header', () => {
            const file = {
                relativePath: 'steering/x.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n# X',
                lineCount: 2,
            };
            const violations = validate('kiro', [file]);
            const headerViolation = violations.find((v) =>
                v.rule.includes('header')
            );
            assert.equal(headerViolation, undefined);
        });

        it('accepts YAML-style header', () => {
            const file = {
                relativePath: 'config/x.json',
                content:
                    '# Auto-generated by generate-adapters' +
                    ' — do not edit manually\n{}',
                lineCount: 2,
            };
            const violations = validate('continue', [file]);
            const headerViolation = violations.find((v) =>
                v.rule.includes('header')
            );
            assert.equal(headerViolation, undefined);
        });
    });

    describe('validate() — Kiro rules', () => {
        it('flags non-.md files in steering/', () => {
            const file = {
                relativePath: 'steering/test.txt',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\ncontent',
                lineCount: 2,
            };
            const violations = validate('kiro', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('.md extension')
            );
            assert.ok(extViolation);
            assert.equal(extViolation.provider, 'kiro');
        });

        it('passes .md files in steering/', () => {
            const file = {
                relativePath: 'steering/implement.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n# Implement',
                lineCount: 2,
            };
            const violations = validate('kiro', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('Kiro steering')
            );
            assert.equal(extViolation, undefined);
        });
    });

    describe('validate() — Cursor rules', () => {
        it('flags non-.md/.mdc files in rules/', () => {
            const file = {
                relativePath: 'rules/test.yaml',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\nrules',
                lineCount: 2,
            };
            const violations = validate('cursor', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('.md or .mdc')
            );
            assert.ok(extViolation);
        });

        it('passes .mdc files in rules/', () => {
            const file = {
                relativePath: 'rules/awos.mdc',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n# Rules',
                lineCount: 2,
            };
            const violations = validate('cursor', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('.md or .mdc')
            );
            assert.equal(extViolation, undefined);
        });

        it('flags empty master rule file', () => {
            const file = {
                relativePath: 'rules/awos.mdc',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n',
                lineCount: 2,
            };
            const violations = validate('cursor', [file]);
            const masterViolation = violations.find((v) =>
                v.rule.includes('master rule')
            );
            assert.ok(masterViolation);
        });
    });

    describe('validate() — Codex rules', () => {
        it('flags non-.md files in tasks/', () => {
            const file = {
                relativePath: 'tasks/implement.json',
                content:
                    '// Auto-generated by generate-adapters' +
                    ' — do not edit manually\n{}',
                lineCount: 2,
            };
            const violations = validate('codex', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('Codex task')
            );
            assert.ok(extViolation);
        });

        it('passes .md files in tasks/', () => {
            const file = {
                relativePath: 'tasks/implement.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n# Task',
                lineCount: 2,
            };
            const violations = validate('codex', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('Codex task')
            );
            assert.equal(extViolation, undefined);
        });
    });

    describe('validate() — Cline rules', () => {
        it('flags non-.md files in rules/', () => {
            const file = {
                relativePath: 'rules/main.yaml',
                content:
                    '# Auto-generated by generate-adapters' +
                    ' — do not edit manually\nrule: yes',
                lineCount: 2,
            };
            const violations = validate('cline', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('Cline rule')
            );
            assert.ok(extViolation);
        });

        it('flags non-.md files in memory-bank/', () => {
            const file = {
                relativePath: 'memory-bank/state.json',
                content:
                    '// Auto-generated by generate-adapters' +
                    ' — do not edit manually\n{}',
                lineCount: 2,
            };
            const violations = validate('cline', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('memory bank')
            );
            assert.ok(extViolation);
        });

        it('passes .md files in memory-bank/', () => {
            const file = {
                relativePath: 'memory-bank/active-context.md',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\n# Context',
                lineCount: 2,
            };
            const violations = validate('cline', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('memory bank')
            );
            assert.equal(extViolation, undefined);
        });
    });

    describe('validate() — Continue rules', () => {
        it('flags non-.json files in config/', () => {
            const file = {
                relativePath: 'config/settings.yaml',
                content:
                    '# Auto-generated by generate-adapters' +
                    ' — do not edit manually\nkey: value',
                lineCount: 2,
            };
            const violations = validate('continue', [file]);
            const extViolation = violations.find((v) =>
                v.rule.includes('.json extension')
            );
            assert.ok(extViolation);
        });

        it('flags invalid JSON in config/ files', () => {
            const file = {
                relativePath: 'config/commands.json',
                content:
                    '// Auto-generated by generate-adapters' +
                    ' — do not edit manually\n{broken: json}',
                lineCount: 2,
            };
            const violations = validate('continue', [file]);
            const jsonViolation = violations.find((v) =>
                v.rule.includes('valid JSON')
            );
            assert.ok(jsonViolation);
            assert.ok(jsonViolation.suggestedFix.includes('Fix JSON'));
        });

        it('passes valid JSON in config/ files', () => {
            const file = {
                relativePath: 'config/commands.json',
                content:
                    '// Auto-generated by generate-adapters' +
                    ' — do not edit manually\n{"commands": []}',
                lineCount: 2,
            };
            const violations = validate('continue', [file]);
            const jsonViolation = violations.find((v) =>
                v.rule.includes('valid JSON')
            );
            assert.equal(jsonViolation, undefined);
        });
    });

    describe('validate() — cross-provider isolation', () => {
        it('does not apply kiro rules to cursor files', () => {
            const file = {
                relativePath: 'steering/test.txt',
                content:
                    '<!-- Auto-generated by generate-adapters' +
                    ' — do not edit manually -->\ncontent',
                lineCount: 2,
            };
            // Running as cursor should not flag kiro steering rules
            const violations = validate('cursor', [file]);
            const kiroViolation = violations.find((v) =>
                v.rule.includes('Kiro')
            );
            assert.equal(kiroViolation, undefined);
        });

        it('collects multiple violations without fail-fast', () => {
            const files = [
                {
                    relativePath: 'steering/a.txt',
                    content: 'no header',
                    lineCount: 1,
                },
                {
                    relativePath: 'steering/b.txt',
                    content: 'also no header',
                    lineCount: 1,
                },
            ];
            const violations = validate('kiro', files);
            // Each file should have header + extension violations
            assert.ok(violations.length >= 4);
        });
    });

    describe('validate() — violation structure', () => {
        it('includes all required fields in violation', () => {
            const file = {
                relativePath: 'steering/test.txt',
                content: 'no header',
                lineCount: 1,
            };
            const violations = validate('kiro', [file]);
            for (const v of violations) {
                assert.equal(typeof v.provider, 'string');
                assert.equal(typeof v.filePath, 'string');
                assert.equal(typeof v.rule, 'string');
                assert.equal(typeof v.suggestedFix, 'string');
                assert.equal(v.provider, 'kiro');
            }
        });
    });
});
