'use strict';

/**
 * Kiro Installer for the multi-IDE adapter layer.
 *
 * Transforms generated adapter files from `.awos-adapters/kiro/` into
 * Kiro-native format and installs them into the project's `.kiro/`
 * directory:
 *   - Steering files  → `.kiro/steering/` (with `inclusion: manual` frontmatter)
 *   - Hook markdown   → `.kiro/hooks/` (converted to JSON hook schema)
 *
 * This completes the "last mile" that generate.js does not handle.
 *
 * @module lib/installers/kiro
 */

const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

/** Kiro steering output directory relative to project root. */
const KIRO_STEERING_DIR = '.kiro/steering';

/** Kiro hooks output directory relative to project root. */
const KIRO_HOOKS_DIR = '.kiro/hooks';

/** Frontmatter prepended to all installed steering files. */
const STEERING_FRONTMATTER = `---\ninclusion: manual\n---\n`;

/** Hook JSON schema version. */
const HOOK_VERSION = '1.0.0';

// ---------------------------------------------------------------------
// Steering Installation
// ---------------------------------------------------------------------

/**
 * Install steering files from the generated adapter directory into
 * `.kiro/steering/`. Adds `inclusion: manual` frontmatter so Kiro
 * exposes them via `#name` in chat.
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @param {Object} [options]
 * @param {boolean} [options.dryRun=false] - If true, returns files without writing
 * @returns {Promise<{installed: string[], skipped: string[], errors: string[]}>}
 */
async function installSteering(projectRoot, options = {}) {
    const { dryRun = false } = options;
    const sourceDir = path.join(projectRoot, '.awos-adapters', 'kiro', 'steering');
    const targetDir = path.join(projectRoot, KIRO_STEERING_DIR);
    const installed = [];
    const skipped = [];
    const errors = [];

    if (!fs.existsSync(sourceDir)) {
        errors.push(`Source directory not found: ${sourceDir}`);
        return { installed, skipped, errors };
    }

    if (!dryRun) {
        await fsp.mkdir(targetDir, { recursive: true });
    }

    const entries = await fsp.readdir(sourceDir);
    const mdFiles = entries.filter((f) => f.endsWith('.md'));

    for (const file of mdFiles) {
        const sourcePath = path.join(sourceDir, file);
        const targetPath = path.join(targetDir, file);

        try {
            let content = await fsp.readFile(sourcePath, 'utf8');

            // Strip the auto-generated HTML comment header if present
            content = content.replace(
                /^<!-- Auto-generated by generate-adapters — do not edit manually -->\s*\n*/,
                ''
            );

            // Replace /awos: command references with # references for Kiro
            content = content.replace(/`\/awos:(\w+)`/g, '`#$1`');
            content = content.replace(/\/awos:(\w+)/g, '#$1');

            // Prepend the Kiro steering frontmatter
            const finalContent = STEERING_FRONTMATTER + content;

            if (!dryRun) {
                await fsp.writeFile(targetPath, finalContent, 'utf8');
            }

            installed.push(file);
        } catch (err) {
            errors.push(`Failed to install ${file}: ${err.message}`);
        }
    }

    return { installed, skipped, errors };
}

// ---------------------------------------------------------------------
// Hook Installation
// ---------------------------------------------------------------------

/**
 * Map of AWOS command names to their hook configurations.
 * Each command that has a generated hook markdown file gets a
 * corresponding JSON hook in `.kiro/hooks/`.
 */
const HOOK_PROMPTS = {
    product: {
        description: 'Define the product — what, why, and for who.',
        prompt:
            'Follow the instructions in the #product steering file. ' +
            'Run the product definition workflow now. Check if ' +
            'context/product/product-definition.md exists to decide creation vs update mode. ' +
            'Use the template at .awos/templates/product-definition-template.md.',
    },
    roadmap: {
        description: 'Build the product roadmap — features and their order.',
        prompt:
            'Follow the instructions in the #roadmap steering file. ' +
            'Run the roadmap workflow now. Check if context/product/roadmap.md exists ' +
            'to decide creation vs update mode. ' +
            'Use the template at .awos/templates/roadmap-template.md.',
    },
    architecture: {
        description: 'Define system architecture — stack, DBs, infra.',
        prompt:
            'Follow the instructions in the #architecture steering file. ' +
            'Run the architecture workflow now. Check if context/product/architecture.md ' +
            'exists to decide creation vs update mode. ' +
            'Use the template at .awos/templates/architecture-template.md.',
    },
    hire: {
        description: 'Hire specialist agents — find and install skills, MCPs, and agents.',
        prompt:
            'Follow the instructions in the #hire steering file. ' +
            'Run the hire workflow now. Analyze the architecture and technical specs ' +
            'to identify needed agents, check what exists, and install missing components.',
    },
    spec: {
        description: 'Create a functional spec — what the feature does for the user.',
        prompt:
            'Follow the instructions in the #spec steering file. ' +
            'Run the spec creation workflow now. Determine the topic from my prompt ' +
            'or the roadmap, then guide me through creating a functional specification. ' +
            'Use the template at .awos/templates/functional-spec-template.md.',
    },
    tech: {
        description: 'Create the technical spec — how the feature will be built.',
        prompt:
            'Follow the instructions in the #tech steering file. ' +
            'Run the technical specification workflow now. Identify the target spec, ' +
            'analyze context, and guide me through creating the technical considerations. ' +
            'Use the template at .awos/templates/technical-considerations-template.md.',
    },
    tasks: {
        description: 'Break the tech spec into a vertically-sliced task list.',
        prompt:
            'Follow the instructions in the #tasks steering file. ' +
            'Run the task planning workflow now. Identify the target spec, read its ' +
            'functional and technical specs, then generate a vertically-sliced task list ' +
            'with agent assignments.',
    },
    implement: {
        description: 'Run tasks — delegate coding to sub-agents and track progress.',
        prompt:
            'Follow the instructions in the #implement steering file. ' +
            'Run the implementation workflow now. Find the next incomplete spec, ' +
            'load context, and start delegating tasks to sub-agents in order. ' +
            'Mark tasks complete as they finish.',
    },
    verify: {
        description: 'Verify spec completion — check acceptance criteria and mark as Completed.',
        prompt:
            'Follow the instructions in the #verify steering file. ' +
            'Run the verification workflow now. Find the spec that is ready for ' +
            'verification, check each acceptance criterion against the implementation, ' +
            'and mark verified criteria as done.',
    },
};

/**
 * Install hooks from generated adapter directory into `.kiro/hooks/`.
 * Creates a `userTriggered` JSON hook for each AWOS command that has
 * a steering file, plus `postTaskExecution` hooks for commands that
 * have delegation (implement, tasks, tech, hire).
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @param {Object} [options]
 * @param {boolean} [options.dryRun=false] - If true, returns files without writing
 * @returns {Promise<{installed: string[], errors: string[]}>}
 */
async function installHooks(projectRoot, options = {}) {
    const { dryRun = false } = options;
    const steeringSource = path.join(projectRoot, '.awos-adapters', 'kiro', 'steering');
    const hookSource = path.join(projectRoot, '.awos-adapters', 'kiro', 'hooks');
    const targetDir = path.join(projectRoot, KIRO_HOOKS_DIR);
    const installed = [];
    const errors = [];

    if (!dryRun) {
        await fsp.mkdir(targetDir, { recursive: true });
    }

    // 1. Create userTriggered hooks for each steering file
    if (fs.existsSync(steeringSource)) {
        const entries = await fsp.readdir(steeringSource);
        const mdFiles = entries.filter((f) => f.endsWith('.md'));

        for (const file of mdFiles) {
            const commandName = path.basename(file, '.md');
            const hookConfig = HOOK_PROMPTS[commandName];

            if (!hookConfig) continue;

            const hook = {
                name: `AWOS: ${capitalize(commandName)}`,
                version: HOOK_VERSION,
                description: hookConfig.description,
                when: {
                    type: 'userTriggered',
                },
                then: {
                    type: 'askAgent',
                    prompt: hookConfig.prompt,
                },
            };

            const hookFileName = `awos-${commandName}.json`;
            const targetPath = path.join(targetDir, hookFileName);

            try {
                if (!dryRun) {
                    await fsp.writeFile(
                        targetPath,
                        JSON.stringify(hook, null, 2) + '\n',
                        'utf8'
                    );
                }
                installed.push(hookFileName);
            } catch (err) {
                errors.push(`Failed to install hook ${hookFileName}: ${err.message}`);
            }
        }
    }

    // 2. Create postTaskExecution hooks from hook markdown files
    if (fs.existsSync(hookSource)) {
        const entries = await fsp.readdir(hookSource);
        const hookMdFiles = entries.filter((f) => f.endsWith('.md'));

        for (const file of hookMdFiles) {
            const baseName = path.basename(file, '.md');
            // e.g. "implement-post-task" → command "implement"
            const commandName = baseName.replace(/-post-task$/, '');

            const hook = {
                name: `AWOS: Post-Task — ${capitalize(commandName)}`,
                version: HOOK_VERSION,
                description:
                    `After all tasks complete for ${commandName}: announce status ` +
                    'and suggest running verify.',
                when: {
                    type: 'postTaskExecution',
                },
                then: {
                    type: 'askAgent',
                    prompt:
                        `All tasks have been marked complete. ` +
                        `Announce the completion status with task count and percentage. ` +
                        `Suggest running the #verify workflow to validate acceptance criteria.`,
                },
            };

            const hookFileName = `awos-${baseName}.json`;
            const targetPath = path.join(targetDir, hookFileName);

            try {
                if (!dryRun) {
                    await fsp.writeFile(
                        targetPath,
                        JSON.stringify(hook, null, 2) + '\n',
                        'utf8'
                    );
                }
                installed.push(hookFileName);
            } catch (err) {
                errors.push(`Failed to install hook ${hookFileName}: ${err.message}`);
            }
        }
    }

    return { installed, errors };
}

// ---------------------------------------------------------------------
// Overlay Installation
// ---------------------------------------------------------------------

/** Kiro skills output directory relative to project root. */
const KIRO_SKILLS_DIR = '.kiro/skills';

/**
 * Protected directory prefixes relative to project root.
 * No overlay file writes are permitted under these paths.
 */
const PROTECTED_DIRS = ['.awos', 'commands', 'plugins', 'templates', 'src'];

/**
 * Check whether a target path falls under a protected directory.
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @param {string} targetPath - Absolute or relative path to check
 * @returns {boolean} true if the path is under a protected directory
 */
function isProtectedPath(projectRoot, targetPath) {
    const resolvedRoot = path.resolve(projectRoot);
    const resolvedTarget = path.resolve(targetPath);

    for (const dir of PROTECTED_DIRS) {
        const protectedPrefix = resolvedRoot + path.sep + dir + path.sep;
        const protectedExact = resolvedRoot + path.sep + dir;
        if (resolvedTarget === protectedExact || resolvedTarget.startsWith(protectedPrefix)) {
            return true;
        }
    }
    return false;
}

/** Kiro MCP configuration file path relative to project root. */
const KIRO_MCP_PATH = '.kiro/settings/mcp.json';

/**
 * @typedef {Object} OverlayInstallResult
 * @property {string[]} skills - Skill names installed
 * @property {string[]} agents - Agent names installed
 * @property {string[]} mcps - MCP server names installed
 * @property {string[]} warnings - Non-fatal issues
 * @property {string[]} errors - Fatal issues per resource
 */

/**
 * Extract YAML frontmatter from a markdown file content.
 * Looks for content between opening `---\n` and closing `\n---\n` (or `\n---` at EOF).
 *
 * @param {string} content - File content
 * @returns {string|null} Raw frontmatter string or null if not found
 */
function extractFrontmatter(content) {
    if (!content.startsWith('---\n') && !content.startsWith('---\r\n')) {
        return null;
    }
    const endMarker = content.indexOf('\n---\n', 4);
    const endMarkerEof = content.indexOf('\n---', 4);
    if (endMarker !== -1) {
        return content.slice(4, endMarker);
    }
    // Handle case where --- is at end of file without trailing newline
    if (endMarkerEof !== -1 && (endMarkerEof + 4 === content.length || content.slice(endMarkerEof + 4).trim() === '')) {
        return content.slice(4, endMarkerEof);
    }
    return null;
}

/**
 * Extract a field value from raw YAML frontmatter content.
 * Simple line-based extraction — no full YAML parser needed.
 *
 * @param {string} frontmatter - Raw frontmatter string
 * @param {string} field - Field name to extract
 * @returns {string|null} Field value or null if not found
 */
function extractFrontmatterField(frontmatter, field) {
    const lines = frontmatter.split('\n');
    for (const line of lines) {
        const match = line.match(new RegExp(`^${field}:\\s*(.+)$`));
        if (match) {
            return match[1].trim().replace(/^['"]|['"]$/g, '');
        }
    }
    return null;
}

/**
 * Install overlay resources into .kiro/ structure.
 *
 * Currently implements skill installation. Agent and MCP installation
 * will be added in subsequent tasks.
 *
 * @param {string} projectRoot
 * @param {Array<{name: string, type: string, absolutePath: string, description?: string, tags?: string[], source?: string}>} resources - Pre-validated overlay resources
 * @param {Object} [options]
 * @param {boolean} [options.dryRun=false]
 * @returns {Promise<OverlayInstallResult>}
 */
async function installOverlay(projectRoot, resources, options = {}) {
    const { dryRun = false } = options;

    /** @type {OverlayInstallResult} */
    const result = {
        skills: [],
        agents: [],
        mcps: [],
        warnings: [],
        errors: [],
    };

    // --- Skill Installation ---
    const skillResources = resources.filter((r) => r.type === 'skill');

    for (const resource of skillResources) {
        try {
            const content = await fsp.readFile(resource.absolutePath, 'utf8');
            const frontmatter = extractFrontmatter(content);

            if (!frontmatter) {
                result.warnings.push(
                    `Skill "${resource.name}": missing YAML frontmatter in ${resource.absolutePath}`
                );
                continue;
            }

            const skillName = extractFrontmatterField(frontmatter, 'name');

            if (!skillName) {
                result.warnings.push(
                    `Skill "${resource.name}": missing "name" field in frontmatter of ${resource.absolutePath}`
                );
                continue;
            }

            const targetDir = path.join(projectRoot, KIRO_SKILLS_DIR, skillName);
            const sourceFilename = path.basename(resource.absolutePath);
            const targetPath = path.join(targetDir, sourceFilename);

            if (isProtectedPath(projectRoot, targetPath)) {
                result.errors.push(
                    `Skill "${resource.name}": target path "${targetPath}" is under a protected directory`
                );
                continue;
            }

            if (!dryRun) {
                await fsp.mkdir(targetDir, { recursive: true });
                await fsp.copyFile(resource.absolutePath, targetPath);
            }

            result.skills.push(skillName);
        } catch (err) {
            result.errors.push(
                `Skill "${resource.name}": ${err.message}`
            );
        }
    }

    // --- Agent Installation ---
    const agentResources = resources.filter((r) => r.type === 'agent');
    const overlaySkillNames = new Set(
        resources.filter((r) => r.type === 'skill').map((r) => r.name)
    );

    for (const resource of agentResources) {
        try {
            const content = await fsp.readFile(resource.absolutePath, 'utf8');
            const frontmatter = extractFrontmatter(content);

            if (!frontmatter) {
                result.warnings.push(
                    `Agent "${resource.name}": missing YAML frontmatter in ${resource.absolutePath}`
                );
                continue;
            }

            const agentName = extractFrontmatterField(frontmatter, 'name');
            const description = extractFrontmatterField(frontmatter, 'description') || '';
            const skillsRaw = extractFrontmatterField(frontmatter, 'skills') || '';

            if (!agentName) {
                result.warnings.push(
                    `Agent "${resource.name}": missing "name" field in frontmatter of ${resource.absolutePath}`
                );
                continue;
            }

            // Parse skills as comma-separated list
            const skillsList = skillsRaw
                .split(',')
                .map((s) => s.trim())
                .filter((s) => s.length > 0);

            // Verify each skill exists in overlay resources or on disk
            const missingSkills = [];
            for (const skillName of skillsList) {
                const inOverlay = overlaySkillNames.has(skillName);
                if (!inOverlay) {
                    const skillDir = path.join(projectRoot, KIRO_SKILLS_DIR, skillName);
                    if (!fs.existsSync(skillDir)) {
                        missingSkills.push(skillName);
                    }
                }
            }

            if (missingSkills.length > 0) {
                result.warnings.push(
                    `Agent "${agentName}": missing skill dependencies: ${missingSkills.join(', ')}. Skipping agent.`
                );
                continue;
            }

            // Generate steering file
            const steeringDir = path.join(projectRoot, KIRO_STEERING_DIR);
            const steeringPath = path.join(steeringDir, `${agentName}.md`);

            if (isProtectedPath(projectRoot, steeringPath)) {
                result.errors.push(
                    `Agent "${resource.name}": target path "${steeringPath}" is under a protected directory`
                );
                continue;
            }

            const skillsSection = skillsList.map((s) => `- ${s}`).join('\n');
            const steeringContent =
                `---\ninclusion: manual\n---\n\n# ${agentName}\n\n` +
                `> ${description}\n\n` +
                `## Skills\n\n${skillsSection}\n\n` +
                `## Instructions\n\n` +
                `This agent specializes in ${description}.\n` +
                `Activate with \`#${agentName}\` in chat.\n`;

            if (!dryRun) {
                await fsp.mkdir(steeringDir, { recursive: true });
                await fsp.writeFile(steeringPath, steeringContent, 'utf8');
            }

            result.agents.push(agentName);
        } catch (err) {
            result.errors.push(
                `Agent "${resource.name}": ${err.message}`
            );
        }
    }

    // --- MCP Installation ---
    const mcpResources = resources.filter((r) => r.type === 'mcp');

    if (mcpResources.length > 0) {
        const mcpFilePath = path.join(projectRoot, KIRO_MCP_PATH);

        // Read existing mcp.json or start fresh
        let mcpConfig = { mcpServers: {} };
        try {
            const existingContent = await fsp.readFile(mcpFilePath, 'utf8');
            const parsed = JSON.parse(existingContent);
            if (parsed && typeof parsed === 'object') {
                mcpConfig = parsed;
                if (!mcpConfig.mcpServers || typeof mcpConfig.mcpServers !== 'object') {
                    mcpConfig.mcpServers = {};
                }
            }
        } catch (err) {
            if (err.code === 'ENOENT') {
                // File doesn't exist — start with empty config
            } else if (err instanceof SyntaxError) {
                result.warnings.push(
                    `MCP: existing ${KIRO_MCP_PATH} has invalid JSON, starting fresh`
                );
            } else {
                result.warnings.push(
                    `MCP: could not read ${KIRO_MCP_PATH}: ${err.message}, starting fresh`
                );
            }
            mcpConfig = { mcpServers: {} };
        }

        let mcpModified = false;

        for (const resource of mcpResources) {
            try {
                const content = await fsp.readFile(resource.absolutePath, 'utf8');

                let serverEntries;
                try {
                    serverEntries = JSON.parse(content);
                } catch (parseErr) {
                    result.warnings.push(
                        `MCP "${resource.name}": invalid JSON in ${resource.absolutePath}`
                    );
                    continue;
                }

                if (!serverEntries || typeof serverEntries !== 'object' || Array.isArray(serverEntries)) {
                    result.warnings.push(
                        `MCP "${resource.name}": expected a JSON object with server entries in ${resource.absolutePath}`
                    );
                    continue;
                }

                for (const serverName of Object.keys(serverEntries)) {
                    if (mcpConfig.mcpServers[serverName]) {
                        result.warnings.push(
                            `MCP "${resource.name}": server "${serverName}" already exists in ${KIRO_MCP_PATH}, skipping`
                        );
                        continue;
                    }

                    mcpConfig.mcpServers[serverName] = serverEntries[serverName];
                    result.mcps.push(serverName);
                    mcpModified = true;
                }
            } catch (err) {
                result.errors.push(
                    `MCP "${resource.name}": ${err.message}`
                );
            }
        }

        if (mcpModified && !dryRun) {
            if (isProtectedPath(projectRoot, mcpFilePath)) {
                result.errors.push(
                    `MCP: target path "${mcpFilePath}" is under a protected directory`
                );
            } else {
                const mcpDir = path.dirname(mcpFilePath);
                await fsp.mkdir(mcpDir, { recursive: true });
                await fsp.writeFile(mcpFilePath, JSON.stringify(mcpConfig, null, 2), 'utf8');
            }
        }
    }

    return result;
}

// ---------------------------------------------------------------------
// Full Install
// ---------------------------------------------------------------------

const { discover } = require('../resource-resolver');

/**
 * Run the complete Kiro installation: steering + hooks + overlay.
 *
 * The overlay phase runs after steering and hooks. It discovers company
 * overlay resources from `.awos-company/manifest.json` and installs them
 * into `.kiro/`. If no overlay exists, the overlay result is empty and
 * no filesystem operations occur.
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @param {Object} [options]
 * @param {boolean} [options.dryRun=false] - If true, returns results without writing
 * @returns {Promise<{steering: Object, hooks: Object, overlay: OverlayInstallResult}>}
 */
async function install(projectRoot, options = {}) {
    const steeringResult = await installSteering(projectRoot, options);
    const hooksResult = await installHooks(projectRoot, options);

    // Overlay phase — runs after standard installation
    let overlayResult = { skills: [], agents: [], mcps: [], warnings: [], errors: [] };
    const discoveryResult = discover(projectRoot);

    if (discoveryResult.resources.length > 0 && discoveryResult.errors.length === 0) {
        overlayResult = await installOverlay(projectRoot, discoveryResult.resources, options);
        // Include discovery warnings in overlay result
        overlayResult.warnings = [...discoveryResult.warnings, ...overlayResult.warnings];
    } else if (discoveryResult.errors.length > 0) {
        overlayResult.errors = discoveryResult.errors;
        overlayResult.warnings = discoveryResult.warnings;
    }

    return {
        steering: steeringResult,
        hooks: hooksResult,
        overlay: overlayResult,
    };
}

// ---------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------

/**
 * Capitalize the first letter of a string.
 * @param {string} str
 * @returns {string}
 */
function capitalize(str) {
    if (!str) return str;
    return str.charAt(0).toUpperCase() + str.slice(1);
}

// ---------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------

module.exports = {
    install,
    installSteering,
    installHooks,
    installOverlay,
    isProtectedPath,
    KIRO_STEERING_DIR,
    KIRO_HOOKS_DIR,
    KIRO_SKILLS_DIR,
    KIRO_MCP_PATH,
    PROTECTED_DIRS,
};
