/**
 * Configuration for AWOS setup process
 * Defines directories to create and file copy operations
 */

/**
 * Directories to create during setup
 * tools: array of tool names this directory applies to ('claude', 'copilot')
 * When tool='all' is selected, all directories are included automatically
 */
const directories = [
  {
    path: '.awos',
    description: 'AWOS configuration directory',
    tools: ['claude', 'copilot'],
  },
  {
    path: '.claude',
    description: 'Claude configuration directory',
    tools: ['claude'],
  },
  {
    path: '.github/prompts',
    description: 'Copilot prompts directory',
    tools: ['copilot'],
  },
  {
    path: '.vscode',
    description: 'VS Code configuration directory',
    tools: ['copilot'],
  },
  {
    path: 'context',
    description: 'A home for project documentation',
    tools: ['claude', 'copilot'],
  },
  {
    path: 'context/product',
    description: 'Global product definitions',
    tools: ['claude', 'copilot'],
  },
  {
    path: 'context/spec',
    description: 'A home for specifications',
    tools: ['claude', 'copilot'],
  },
];

/**
 * File copy operations to perform during setup
 * Each operation defines what to copy from source to destination
 * tools: array of tool names this operation applies to ('claude', 'copilot')
 * When tool='all' is selected, all operations are included automatically
 */
const copyOperations = [
  // Shared AWOS core (always installed for references)
  {
    source: 'commands',
    destination: '.awos/commands',
    patterns: ['*'],
    description: 'AWOS command prompts',
    tools: ['claude', 'copilot'],
  },
  {
    source: 'templates',
    destination: '.awos/templates',
    patterns: ['*'],
    description: 'AWOS templates',
    tools: ['claude', 'copilot'],
  },
  {
    source: 'scripts',
    destination: '.awos/scripts',
    patterns: ['*'],
    description: 'AWOS scripts',
    tools: ['claude', 'copilot'],
  },
  {
    source: 'claude/commands',
    destination: '.claude/commands/awos',
    patterns: ['*'],
    description: 'Claude Code commands',
    tools: ['claude'],
  },
  // Note: Copilot prompts are generated by prompt-generator.js (not copied directly)
  // because Copilot doesn't resolve file references - content must be inlined
];

/**
 * Filter copy operations by selected tool
 * @param {Array} operations - Copy operations array
 * @param {string} tool - Selected tool ('claude', 'copilot', 'all')
 * @returns {Array} Filtered operations (all operations when tool='all')
 */
function filterOperationsByTool(operations, tool) {
  if (tool === 'all') return operations;
  return operations.filter((op) => {
    if (!op.tools) return true;
    return op.tools.includes(tool);
  });
}

/**
 * Filter directories by selected tool
 * @param {Array} dirs - Directories array
 * @param {string} tool - Selected tool ('claude', 'copilot', 'all')
 * @returns {Array} Filtered directories (all directories when tool='all')
 */
function filterDirectoriesByTool(dirs, tool) {
  if (tool === 'all') return dirs;
  return dirs.filter((dir) => {
    if (!dir.tools) return true;
    return dir.tools.includes(tool);
  });
}

module.exports = {
  directories,
  copyOperations,
  filterOperationsByTool,
  filterDirectoriesByTool,
};
