'use strict';

/**
 * Intermediate Representation module for the multi-IDE adapter layer.
 *
 * Defines the provider-neutral data structures produced by the parser
 * and consumed by all emitters. Includes JSON serialization/deserialization
 * for debugging (--dump-ir) and round-trip validation.
 *
 * @module lib/ir
 */

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

/**
 * Header comment inserted at the top of every generated adapter file.
 * @type {string}
 */
const AUTO_GENERATED_HEADER =
    '// Auto-generated by generate-adapters — do not edit manually';

/**
 * Valid tool names that can appear in ToolReference objects.
 * @type {ReadonlyArray<string>}
 */
const VALID_TOOLS = Object.freeze([
    'Agent',
    'Read',
    'Glob',
    'AskUserQuestion',
    'Explore',
    'Plan',
]);

// ---------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------

/**
 * Create a new CommandIR with sensible defaults.
 * All sections are initialized to empty/neutral values so consumers
 * can populate only the fields they need.
 *
 * @param {string} name - Command name (derived from filename)
 * @returns {CommandIR}
 */
function createCommandIR(name) {
    if (typeof name !== 'string' || name.length === 0) {
        throw new Error('createCommandIR: name must be a non-empty string');
    }

    return {
        name,
        frontmatter: {
            description: null,
            argumentHint: null,
        },
        role: {
            title: '',
            description: '',
            rules: [],
        },
        task: {
            goal: '',
            body: '',
        },
        io: {
            inputs: [],
            outputs: [],
            contextFiles: [],
        },
        interaction: {
            tools: [],
            notes: '',
        },
        process: {
            steps: [],
        },
        toolReferences: [],
    };
}

// ---------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------

/**
 * Serialize a CommandIR to a JSON string.
 * Used by --dump-ir and round-trip testing.
 *
 * @param {CommandIR} ir
 * @returns {string} Pretty-printed JSON string
 */
function serialize(ir) {
    if (!ir || typeof ir !== 'object') {
        throw new Error('serialize: ir must be a non-null object');
    }
    if (typeof ir.name !== 'string') {
        throw new Error('serialize: ir.name must be a string');
    }
    return JSON.stringify(ir, null, 2);
}

// ---------------------------------------------------------------------
// Deserialization & Validation
// ---------------------------------------------------------------------

/**
 * Deserialize a JSON string back into a CommandIR.
 * Validates that required fields are present and correctly typed.
 *
 * @param {string} json - JSON string previously produced by serialize()
 * @returns {CommandIR}
 * @throws {Error} On invalid JSON or missing/malformed required fields
 */
function deserialize(json) {
    if (typeof json !== 'string') {
        throw new Error('deserialize: input must be a JSON string');
    }

    let obj;
    try {
        obj = JSON.parse(json);
    } catch (err) {
        throw new Error(`deserialize: invalid JSON — ${err.message}`);
    }

    validateCommandIR(obj);
    return obj;
}

/**
 * Validate that an object conforms to the CommandIR shape.
 * Throws on the first structural violation found.
 *
 * @param {unknown} obj
 * @throws {Error} With a descriptive message about what is missing/wrong
 */
function validateCommandIR(obj) {
    if (!obj || typeof obj !== 'object') {
        throw new Error('validateCommandIR: input must be a non-null object');
    }

    // Top-level required fields
    requireString(obj, 'name');
    requireObject(obj, 'frontmatter');
    requireObject(obj, 'role');
    requireObject(obj, 'task');
    requireObject(obj, 'io');
    requireObject(obj, 'interaction');
    requireObject(obj, 'process');
    requireArray(obj, 'toolReferences');

    // Frontmatter
    validateFrontmatter(obj.frontmatter);

    // Role
    validateRoleSection(obj.role);

    // Task
    validateTaskSection(obj.task);

    // IO
    validateIOSection(obj.io);

    // Interaction
    validateInteractionSection(obj.interaction);

    // Process
    validateProcessSection(obj.process);

    // Tool references
    obj.toolReferences.forEach((ref, i) => {
        validateToolReference(ref, `toolReferences[${i}]`);
    });
}

/**
 * @param {unknown} fm
 */
function validateFrontmatter(fm) {
    if (fm.description !== null && typeof fm.description !== 'string') {
        throw new Error(
            'frontmatter.description must be a string or null'
        );
    }
    if (fm.argumentHint !== null && typeof fm.argumentHint !== 'string') {
        throw new Error(
            'frontmatter.argumentHint must be a string or null'
        );
    }
}

/**
 * @param {unknown} role
 */
function validateRoleSection(role) {
    if (typeof role.title !== 'string') {
        throw new Error('role.title must be a string');
    }
    if (typeof role.description !== 'string') {
        throw new Error('role.description must be a string');
    }
    if (!Array.isArray(role.rules)) {
        throw new Error('role.rules must be an array');
    }
}

/**
 * @param {unknown} task
 */
function validateTaskSection(task) {
    if (typeof task.goal !== 'string') {
        throw new Error('task.goal must be a string');
    }
    if (typeof task.body !== 'string') {
        throw new Error('task.body must be a string');
    }
}

/**
 * @param {unknown} io
 */
function validateIOSection(io) {
    if (!Array.isArray(io.inputs)) {
        throw new Error('io.inputs must be an array');
    }
    if (!Array.isArray(io.outputs)) {
        throw new Error('io.outputs must be an array');
    }
    if (!Array.isArray(io.contextFiles)) {
        throw new Error('io.contextFiles must be an array');
    }
    io.inputs.forEach((input, i) => {
        if (typeof input.name !== 'string') {
            throw new Error(`io.inputs[${i}].name must be a string`);
        }
        if (typeof input.optional !== 'boolean') {
            throw new Error(`io.inputs[${i}].optional must be a boolean`);
        }
        if (typeof input.source !== 'string') {
            throw new Error(`io.inputs[${i}].source must be a string`);
        }
    });
    io.outputs.forEach((output, i) => {
        if (typeof output.name !== 'string') {
            throw new Error(`io.outputs[${i}].name must be a string`);
        }
        if (typeof output.description !== 'string') {
            throw new Error(`io.outputs[${i}].description must be a string`);
        }
    });
}

/**
 * @param {unknown} interaction
 */
function validateInteractionSection(interaction) {
    if (!Array.isArray(interaction.tools)) {
        throw new Error('interaction.tools must be an array');
    }
    if (typeof interaction.notes !== 'string') {
        throw new Error('interaction.notes must be a string');
    }
}

/**
 * @param {unknown} process
 */
function validateProcessSection(process) {
    if (!Array.isArray(process.steps)) {
        throw new Error('process.steps must be an array');
    }
    process.steps.forEach((step, i) => {
        validateProcessStep(step, `process.steps[${i}]`);
    });
}

/**
 * @param {unknown} step
 * @param {string} path
 */
function validateProcessStep(step, path) {
    if (!step || typeof step !== 'object') {
        throw new Error(`${path} must be an object`);
    }
    if (typeof step.stepNumber !== 'number') {
        throw new Error(`${path}.stepNumber must be a number`);
    }
    if (typeof step.title !== 'string') {
        throw new Error(`${path}.title must be a string`);
    }
    if (typeof step.body !== 'string') {
        throw new Error(`${path}.body must be a string`);
    }
    if (!Array.isArray(step.toolReferences)) {
        throw new Error(`${path}.toolReferences must be an array`);
    }
    step.toolReferences.forEach((ref, j) => {
        validateToolReference(ref, `${path}.toolReferences[${j}]`);
    });
    if (!Array.isArray(step.delegations)) {
        throw new Error(`${path}.delegations must be an array`);
    }
    step.delegations.forEach((del, j) => {
        validateDelegationCall(del, `${path}.delegations[${j}]`);
    });
}

/**
 * @param {unknown} ref
 * @param {string} path
 */
function validateToolReference(ref, path) {
    if (!ref || typeof ref !== 'object') {
        throw new Error(`${path} must be an object`);
    }
    if (typeof ref.tool !== 'string' || !VALID_TOOLS.includes(ref.tool)) {
        throw new Error(
            `${path}.tool must be one of: ${VALID_TOOLS.join(', ')}`
        );
    }
    if (typeof ref.context !== 'string') {
        throw new Error(`${path}.context must be a string`);
    }
    if (typeof ref.lineNumber !== 'number') {
        throw new Error(`${path}.lineNumber must be a number`);
    }
    if (!ref.parameters || typeof ref.parameters !== 'object') {
        throw new Error(`${path}.parameters must be an object`);
    }
}

/**
 * @param {unknown} del
 * @param {string} path
 */
function validateDelegationCall(del, path) {
    if (!del || typeof del !== 'object') {
        throw new Error(`${path} must be an object`);
    }
    if (typeof del.agentType !== 'string') {
        throw new Error(`${path}.agentType must be a string`);
    }
    if (typeof del.promptTemplate !== 'string') {
        throw new Error(`${path}.promptTemplate must be a string`);
    }
}

// ---------------------------------------------------------------------
// Validation Helpers
// ---------------------------------------------------------------------

function requireString(obj, field) {
    if (typeof obj[field] !== 'string') {
        throw new Error(`${field} must be a string`);
    }
}

function requireObject(obj, field) {
    if (!obj[field] || typeof obj[field] !== 'object' || Array.isArray(obj[field])) {
        throw new Error(`${field} must be a non-null object`);
    }
}

function requireArray(obj, field) {
    if (!Array.isArray(obj[field])) {
        throw new Error(`${field} must be an array`);
    }
}

// ---------------------------------------------------------------------
// Auto-Generated Header Utility
// ---------------------------------------------------------------------

/**
 * Returns the auto-generated header comment string appropriate for the
 * given file type. Defaults to JS-style comment.
 *
 * @param {'js'|'md'|'json'|'yaml'} [format='js'] - File format
 * @returns {string} The header comment line
 */
function getAutoGeneratedHeader(format = 'js') {
    const message =
        'Auto-generated by generate-adapters — do not edit manually';
    switch (format) {
        case 'md':
            return `<!-- ${message} -->`;
        case 'yaml':
            return `# ${message}`;
        case 'json':
            // JSON doesn't support comments; return empty for JSON files
            return '';
        case 'js':
        default:
            return `// ${message}`;
    }
}

// ---------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------

module.exports = {
    AUTO_GENERATED_HEADER,
    VALID_TOOLS,
    createCommandIR,
    serialize,
    deserialize,
    getAutoGeneratedHeader,
};
