'use strict';

/**
 * File Splitter module for the multi-IDE adapter layer.
 *
 * Enforces the 500-line file size constraint by splitting large generated
 * files at section boundaries (H2/H3 headings). Fragments under 10 lines
 * are merged with their adjacent fragment (preferring previous).
 *
 * @module lib/splitter
 */

const { getAutoGeneratedHeader } = require('./ir.js');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

/** Default maximum lines per file. */
const DEFAULT_MAX_LINES = 500;

/** Minimum fragment size — smaller fragments get merged. */
const MIN_FRAGMENT_LINES = 10;

/** Regex matching H2 or H3 markdown headings at the start of a line. */
const HEADING_RE = /^#{2,3}\s+(.+)$/;

// ---------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------

/**
 * Split a generated file if it exceeds maxLines.
 *
 * @param {GeneratedFile} file
 * @param {number} [maxLines=500] - Maximum lines per output file
 * @returns {GeneratedFile[]} Original file (single-element) or split parts
 */
function splitIfNeeded(file, maxLines = DEFAULT_MAX_LINES) {
    if (!file || typeof file !== 'object') {
        throw new Error('splitIfNeeded: file must be a non-null object');
    }
    if (typeof file.content !== 'string') {
        throw new Error('splitIfNeeded: file.content must be a string');
    }
    if (typeof file.relativePath !== 'string') {
        throw new Error('splitIfNeeded: file.relativePath must be a string');
    }
    if (typeof maxLines !== 'number' || maxLines < 1) {
        throw new Error('splitIfNeeded: maxLines must be a positive number');
    }

    const lineCount =
        typeof file.lineCount === 'number'
            ? file.lineCount
            : countLines(file.content);

    if (lineCount <= maxLines) {
        return [{ ...file, lineCount }];
    }

    // Split into sections at heading boundaries
    const sections = splitIntoSections(file.content);

    // Build fragments respecting maxLines
    const fragments = buildFragments(sections, maxLines);

    // Merge tiny fragments (<10 lines) with adjacent
    const merged = mergeTinyFragments(fragments);

    // Produce output GeneratedFile objects
    const baseName = deriveBaseName(file.relativePath);
    const ext = deriveExtension(file.relativePath);

    return merged.map((fragment, index) => {
        const sectionSlug = deriveSectionSlug(fragment.title, index);
        const relativePath = `${baseName}-${sectionSlug}${ext}`;
        const header = getAutoGeneratedHeader('md');
        const content = header
            ? `${header}\n\n${fragment.content}`
            : fragment.content;
        const lc = countLines(content);
        return {
            relativePath,
            content,
            lineCount: lc,
        };
    });
}

// ---------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------

/**
 * Split content into sections based on H2/H3 headings.
 * Each section includes its heading line and all content until the next
 * heading of equal or higher level.
 *
 * @param {string} content
 * @returns {{title: string, lines: string[]}[]}
 */
function splitIntoSections(content) {
    const lines = content.split('\n');
    const sections = [];
    let currentTitle = 'intro';
    let currentLines = [];

    for (const line of lines) {
        const match = line.match(HEADING_RE);
        if (match) {
            // Save the previous section if it has content
            if (currentLines.length > 0) {
                sections.push({ title: currentTitle, lines: currentLines });
            }
            currentTitle = match[1].trim();
            currentLines = [line];
        } else {
            currentLines.push(line);
        }
    }

    // Push the final section
    if (currentLines.length > 0) {
        sections.push({ title: currentTitle, lines: currentLines });
    }

    return sections;
}

/**
 * Build fragments from sections, each staying within maxLines.
 * Groups consecutive sections together until adding the next section
 * would exceed the limit.
 *
 * @param {{title: string, lines: string[]}[]} sections
 * @param {number} maxLines
 * @returns {{title: string, content: string, lineCount: number}[]}
 */
function buildFragments(sections, maxLines) {
    if (sections.length === 0) {
        return [];
    }

    const fragments = [];
    let currentTitle = sections[0].title;
    let currentLines = [];

    for (const section of sections) {
        const wouldExceed =
            currentLines.length + section.lines.length > maxLines;

        if (wouldExceed && currentLines.length > 0) {
            // Flush current fragment
            fragments.push({
                title: currentTitle,
                content: currentLines.join('\n'),
                lineCount: currentLines.length,
            });
            currentTitle = section.title;
            currentLines = [...section.lines];
        } else {
            if (currentLines.length === 0) {
                currentTitle = section.title;
            }
            currentLines.push(...section.lines);
        }
    }

    // Flush remaining
    if (currentLines.length > 0) {
        fragments.push({
            title: currentTitle,
            content: currentLines.join('\n'),
            lineCount: currentLines.length,
        });
    }

    return fragments;
}

/**
 * Merge fragments smaller than MIN_FRAGMENT_LINES with their adjacent
 * fragment. Prefers merging with the previous fragment; if there is no
 * previous, merge with the next.
 *
 * @param {{title: string, content: string, lineCount: number}[]} fragments
 * @returns {{title: string, content: string, lineCount: number}[]}
 */
function mergeTinyFragments(fragments) {
    if (fragments.length <= 1) {
        return fragments;
    }

    const merged = [];

    for (let i = 0; i < fragments.length; i++) {
        const frag = fragments[i];

        if (frag.lineCount < MIN_FRAGMENT_LINES) {
            if (merged.length > 0) {
                // Merge with previous (preferred)
                const prev = merged[merged.length - 1];
                prev.content = prev.content + '\n' + frag.content;
                prev.lineCount = countLines(prev.content);
            } else if (i + 1 < fragments.length) {
                // Merge with next
                const next = fragments[i + 1];
                next.content = frag.content + '\n' + next.content;
                next.lineCount = countLines(next.content);
                // Keep the next fragment's title since it's the primary content
            } else {
                // Only fragment — keep as-is
                merged.push(frag);
            }
        } else {
            merged.push(frag);
        }
    }

    return merged;
}

/**
 * Derive the base name from a relative path by removing the extension.
 * E.g. "steering/implement.md" → "steering/implement"
 *
 * @param {string} relativePath
 * @returns {string}
 */
function deriveBaseName(relativePath) {
    const lastDot = relativePath.lastIndexOf('.');
    if (lastDot === -1) {
        return relativePath;
    }
    return relativePath.slice(0, lastDot);
}

/**
 * Derive the file extension from a relative path.
 * E.g. "steering/implement.md" → ".md"
 *
 * @param {string} relativePath
 * @returns {string}
 */
function deriveExtension(relativePath) {
    const lastDot = relativePath.lastIndexOf('.');
    if (lastDot === -1) {
        return '';
    }
    return relativePath.slice(lastDot);
}

/**
 * Convert a section title to a kebab-case slug suitable for filenames.
 * Falls back to "part-{index}" for non-descriptive titles.
 *
 * @param {string} title
 * @param {number} index
 * @returns {string}
 */
function deriveSectionSlug(title, index) {
    if (!title || title === 'intro') {
        return `part-${index + 1}`;
    }

    const slug = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 40);

    return slug || `part-${index + 1}`;
}

/**
 * Count the number of lines in a string.
 *
 * @param {string} content
 * @returns {number}
 */
function countLines(content) {
    if (!content) {
        return 0;
    }
    // Count newlines; a trailing newline doesn't add an extra line
    const lines = content.split('\n');
    return lines.length;
}

// ---------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------

module.exports = {
    splitIfNeeded,
};
