'use strict';

/**
 * Structural validation module for the multi-IDE adapter layer.
 *
 * Validates generated adapter files against Provider-specific rules
 * (file extensions, JSON/YAML validity, directory nesting, size limits,
 * auto-generated headers). Collects all violations without fail-fast.
 *
 * @module lib/validator
 */

const { getAutoGeneratedHeader } = require('./ir');

// ---------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------

/**
 * Maximum allowed lines per generated file.
 * @type {number}
 */
const MAX_LINES = 500;

/**
 * The canonical auto-generated header text (without comment syntax).
 * @type {string}
 */
const HEADER_TEXT =
    'Auto-generated by generate-adapters — do not edit manually';

// ---------------------------------------------------------------------
// Validation Rules
// ---------------------------------------------------------------------

/**
 * @typedef {Object} ValidationRule
 * @property {string} provider - Provider this rule applies to ('*' = all)
 * @property {string} description - Human-readable rule description
 * @property {function(GeneratedFile): ValidationViolation|null} check
 */

/**
 * @typedef {Object} ValidationViolation
 * @property {string} provider - Provider name
 * @property {string} filePath - Path to the violating file
 * @property {string} rule - Rule description that was violated
 * @property {string} suggestedFix - What to do to fix it
 */

/**
 * Check whether file content begins with the auto-generated header
 * in any supported format (js, md, yaml).
 *
 * @param {string} content
 * @returns {boolean}
 */
function hasAutoGeneratedHeader(content) {
    const firstLine = content.split('\n')[0] || '';
    return firstLine.includes(HEADER_TEXT);
}

/**
 * Attempt to parse content as JSON. Returns null on success,
 * or an error message string on failure.
 *
 * @param {string} content
 * @returns {string|null}
 */
function jsonParseError(content) {
    // Strip auto-generated header lines that aren't valid JSON
    const lines = content.split('\n');
    const jsonLines = lines.filter(
        (line) => !line.startsWith('//') && !line.startsWith('<!--')
    );
    const jsonContent = jsonLines.join('\n').trim();

    if (jsonContent.length === 0) {
        return 'File is empty after stripping comments';
    }

    try {
        JSON.parse(jsonContent);
        return null;
    } catch (err) {
        return err.message;
    }
}

/**
 * Get the file extension from a relative path (lowercase, with dot).
 *
 * @param {string} relativePath
 * @returns {string}
 */
function getExtension(relativePath) {
    const lastDot = relativePath.lastIndexOf('.');
    if (lastDot === -1) return '';
    return relativePath.slice(lastDot).toLowerCase();
}

/**
 * Get the top-level directory from a relative path.
 *
 * @param {string} relativePath
 * @returns {string}
 */
function getTopDir(relativePath) {
    const sep = relativePath.indexOf('/');
    if (sep === -1) return '';
    return relativePath.slice(0, sep);
}

/**
 * All validation rules. Each rule applies to a specific provider
 * or all providers (provider = '*').
 *
 * @type {ValidationRule[]}
 */
const VALIDATION_RULES = [
    // --- Universal rules (all providers) ---
    {
        provider: '*',
        description: 'Generated files must not exceed 500 lines',
        check(file) {
            if (file.lineCount > MAX_LINES) {
                return {
                    provider: '',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        `Split the file into multiple parts. ` +
                        `Current: ${file.lineCount} lines, max: ${MAX_LINES}.`,
                };
            }
            return null;
        },
    },
    {
        provider: '*',
        description: 'Generated files must have auto-generated header',
        check(file) {
            if (!hasAutoGeneratedHeader(file.content)) {
                return {
                    provider: '',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        'Add the auto-generated header comment as the first ' +
                        'line of the file.',
                };
            }
            return null;
        },
    },

    // --- Kiro rules ---
    {
        provider: 'kiro',
        description:
            'Kiro steering files must use .md extension',
        check(file) {
            if (
                getTopDir(file.relativePath) === 'steering' &&
                getExtension(file.relativePath) !== '.md'
            ) {
                return {
                    provider: 'kiro',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        `Rename file to use .md extension instead of ` +
                        `'${getExtension(file.relativePath)}'.`,
                };
            }
            return null;
        },
    },
    {
        provider: 'kiro',
        description:
            'Kiro steering files must be in the steering/ directory',
        check(file) {
            const ext = getExtension(file.relativePath);
            if (
                ext === '.md' &&
                getTopDir(file.relativePath) !== 'steering' &&
                getTopDir(file.relativePath) !== ''
            ) {
                // Only flag .md files that look like steering content but are
                // misplaced. Files at root level are allowed (e.g. README).
                return null;
            }
            return null;
        },
    },

    // --- Cursor rules ---
    {
        provider: 'cursor',
        description:
            'Cursor rule files must use .md or .mdc extension',
        check(file) {
            if (getTopDir(file.relativePath) === 'rules') {
                const ext = getExtension(file.relativePath);
                if (ext !== '.md' && ext !== '.mdc') {
                    return {
                        provider: 'cursor',
                        filePath: file.relativePath,
                        rule: this.description,
                        suggestedFix:
                            `Rename file to use .md or .mdc extension ` +
                            `instead of '${ext}'.`,
                    };
                }
            }
            return null;
        },
    },
    {
        provider: 'cursor',
        description:
            'Cursor master rule file must be valid markdown',
        check(file) {
            if (
                file.relativePath === 'rules/awos.mdc' ||
                file.relativePath === 'rules/awos.md'
            ) {
                // Basic markdown validity: must have content beyond the header
                const lines = file.content.split('\n');
                const contentLines = lines.filter(
                    (line) =>
                        !line.includes(HEADER_TEXT) &&
                        line.trim().length > 0
                );
                if (contentLines.length === 0) {
                    return {
                        provider: 'cursor',
                        filePath: file.relativePath,
                        rule: this.description,
                        suggestedFix:
                            'Master rule file must contain valid markdown content.',
                    };
                }
            }
            return null;
        },
    },

    // --- Codex rules ---
    {
        provider: 'codex',
        description: 'Codex task files must use .md extension',
        check(file) {
            if (
                getTopDir(file.relativePath) === 'tasks' &&
                getExtension(file.relativePath) !== '.md'
            ) {
                return {
                    provider: 'codex',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        `Rename file to use .md extension instead of ` +
                        `'${getExtension(file.relativePath)}'.`,
                };
            }
            return null;
        },
    },

    // --- Cline rules ---
    {
        provider: 'cline',
        description: 'Cline rule files must use .md extension',
        check(file) {
            if (
                getTopDir(file.relativePath) === 'rules' &&
                getExtension(file.relativePath) !== '.md'
            ) {
                return {
                    provider: 'cline',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        `Rename file to use .md extension instead of ` +
                        `'${getExtension(file.relativePath)}'.`,
                };
            }
            return null;
        },
    },
    {
        provider: 'cline',
        description:
            'Cline memory bank files must use .md extension',
        check(file) {
            if (
                getTopDir(file.relativePath) === 'memory-bank' &&
                getExtension(file.relativePath) !== '.md'
            ) {
                return {
                    provider: 'cline',
                    filePath: file.relativePath,
                    rule: this.description,
                    suggestedFix:
                        `Rename file to use .md extension instead of ` +
                        `'${getExtension(file.relativePath)}'.`,
                };
            }
            return null;
        },
    },

    // --- Continue rules ---
    {
        provider: 'continue',
        description:
            'Continue config files must use .md or .json extension',
        check(file) {
            if (getTopDir(file.relativePath) === 'config') {
                const ext = getExtension(file.relativePath);
                if (ext !== '.md' && ext !== '.json') {
                    return {
                        provider: 'continue',
                        filePath: file.relativePath,
                        rule: this.description,
                        suggestedFix:
                            `Rename file to use .md or .json extension ` +
                            `instead of '${ext}'.`,
                    };
                }
            }
            return null;
        },
    },
    {
        provider: 'continue',
        description:
            'Continue config files (.json) must contain valid JSON',
        check(file) {
            if (
                getTopDir(file.relativePath) === 'config' &&
                getExtension(file.relativePath) === '.json'
            ) {
                const error = jsonParseError(file.content);
                if (error) {
                    return {
                        provider: 'continue',
                        filePath: file.relativePath,
                        rule: this.description,
                        suggestedFix: `Fix JSON syntax error: ${error}`,
                    };
                }
            }
            return null;
        },
    },
];

// ---------------------------------------------------------------------
// Main Validation Function
// ---------------------------------------------------------------------

/**
 * Validate all generated files for a Provider.
 * Runs all applicable rules and collects all violations (no fail-fast).
 *
 * @param {string} provider - Provider name (e.g. 'kiro', 'cursor')
 * @param {GeneratedFile[]} files - Files to validate
 * @returns {ValidationViolation[]} All violations found
 */
function validate(provider, files) {
    if (typeof provider !== 'string' || provider.length === 0) {
        throw new Error('validate: provider must be a non-empty string');
    }
    if (!Array.isArray(files)) {
        throw new Error('validate: files must be an array');
    }

    const violations = [];

    // Filter rules applicable to this provider
    const applicableRules = VALIDATION_RULES.filter(
        (rule) => rule.provider === '*' || rule.provider === provider
    );

    for (const file of files) {
        for (const rule of applicableRules) {
            const violation = rule.check(file);
            if (violation) {
                // Ensure the provider field is set correctly
                violation.provider = provider;
                violations.push(violation);
            }
        }
    }

    return violations;
}

// ---------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------

module.exports = {
    validate,
    VALIDATION_RULES,
};
