name: Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Get latest release tag and increment patch version
        id: get_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          # Remove 'v' prefix and increment patch version for package.json
          version_without_v=$(echo $latest_tag | sed 's/^v//')
          new_version=$(echo $version_without_v | awk -F. -v OFS=. '{$NF++;print}')
          new_tag="v$new_version"
          echo "New version: $new_version"
          echo "New tag: $new_tag"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Update package.json version
        run: npm version ${{ steps.get_version.outputs.new_version }} --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Publish to npm (dry run)
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create git tag (dry run)
        run: |
          echo "Would create git tag: ${{ steps.get_version.outputs.new_tag }}"
          echo "Would push tag to origin"
        # git tag ${{ steps.get_version.outputs.new_tag }}
        # git push origin ${{ steps.get_version.outputs.new_tag }}

      - name: Create Release (dry run)
        run: |
          echo "Would create GitHub release with tag: ${{ steps.get_version.outputs.new_tag }}"
        # uses: softprops/action-gh-release@v1
        # with:
        #   tag_name: ${{ steps.get_version.outputs.new_tag }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
